import { expect, test, type Page } from '@playwright/test'

async function add(page: Page, format = 'Абонемент', zones = 'both', date = '2099-04-05') {
  const form = page.locator('.offer-preview')
  await form.getByRole('radio', { name: format, exact: true }).check()
  if (zones === 'pool') await form.getByRole('checkbox', { name: /Зал \+ кардио/ }).uncheck()
  if (zones === 'gym') await form.getByRole('checkbox', { name: /Бассейн/ }).uncheck()
  await form.getByLabel(format === 'Абонемент' ? 'Дата начала' : 'Дата посещения', { exact: true }).fill(date)
  await form.getByRole('button', { name: 'Добавить в корзину' }).click()
  await expect(page).toHaveURL(/\/cart$/)
}
async function signIn(page: Page) {
  await page.getByRole('link', { name: 'Войти для оформления' }).click()
  await page.getByRole('button', { name: 'Заполнить демоданные' }).click()
  await page.getByRole('button', { name: 'Войти в аккаунт' }).click()
  await expect(page).toHaveURL(/\/cart$/)
}

test('guest selection, editing, promo validation, converted order, failure/retry and purchased access', async ({ page }, testInfo) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/plans')
  await add(page, 'Абонемент', 'pool')
  await page.getByRole('link', { name: 'Изменить', exact: true }).click()
  await expect(page.getByLabel('Дата начала', { exact: true })).toHaveValue('2099-04-05')
  await expect(page.getByRole('checkbox', { name: /Зал \+ кардио/ })).not.toBeChecked()
  await page.getByLabel('Дата начала', { exact: true }).fill('2099-05-06')
  await page.getByRole('button', { name: 'Сохранить изменения' }).click()
  await signIn(page)
  await expect(page.locator('.commerce-items')).toContainText('6 мая 2099')
  await page.getByLabel('Промокод', { exact: true }).fill('BAD')
  await page.getByRole('button', { name: 'Применить', exact: true }).click()
  await expect(page.getByRole('alert')).toContainText('Промокод не найден')
  await expect(page.getByRole('button', { name: 'Создать заказ и перейти к оплате' })).toBeDisabled()
  await page.getByLabel('Промокод', { exact: true }).fill('FORMA10')
  await page.getByRole('button', { name: 'Применить', exact: true }).click()
  await page.getByLabel('Валюта оплаты').selectOption('USD')
  await expect(page.locator('.purchase-total')).toContainText('66,46')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('cart-ru.png'), fullPage: true })
  await page.setViewportSize({ width: 320, height: 850 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.getByRole('button', { name: 'Создать заказ и перейти к оплате' }).click()
  await expect(page).toHaveURL(/\/account\/orders\/\d+$/)
  await expect(page.locator('.purchase-total')).toContainText('66,46')
  await page.getByRole('radio', { name: 'Отказ оплаты', exact: true }).check()
  await page.getByRole('button', { name: 'Оплатить в деморежиме' }).click()
  await expect(page.getByText('Оплата не прошла. Доступ не выдан.')).toBeVisible()
  await expect(page.locator('.attempt-row')).toHaveCount(1)
  await page.getByRole('radio', { name: 'Успешная оплата', exact: true }).check()
  await page.getByRole('button', { name: 'Повторить оплату', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'Оплата прошла. Доступ появился в кабинете.' })).toBeVisible()
  await expect(page.locator('.attempt-row')).toHaveCount(2)
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('order-en.png'), fullPage: true })
  await page.getByRole('navigation', { name: 'Account navigation' }).getByRole('link', { name: 'My orders' }).click()
  await expect(page.locator('.commerce-card').first()).toContainText('Paid')
  await page.locator('.commerce-card').first().getByRole('link', { name: /Details/ }).click()
  await page.getByRole('link', { name: 'Purchased access 1' }).click()
  await expect(page.getByRole('heading', { name: 'Membership', exact: true })).toBeVisible()
  await expect(page.locator('.zone-badges')).toHaveText('Pool')
  await expect(page.locator('.access-status-pending')).toHaveText('Upcoming')
  await expect(page.locator('.access-dates')).toContainText('May 6, 2099')
  await page.setViewportSize({ width: 320, height: 850 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('access-en-320.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('single visit survives registration, demo verification, removal and successful purchase', async ({ page }, testInfo) => {
  await page.goto('/cart')
  await expect(page.getByRole('heading', { name: 'В корзине пока пусто' })).toBeVisible()
  await page.getByRole('link', { name: /Выбрать посещение/ }).click()
  await add(page, 'Разовое посещение')
  await page.getByRole('button', { name: 'Удалить', exact: true }).click()
  await expect(page.getByRole('heading', { name: 'В корзине пока пусто' })).toBeVisible()
  await page.getByRole('link', { name: /Выбрать посещение/ }).click()
  await add(page, 'Разовое посещение')
  await page.getByRole('link', { name: 'Войти для оформления' }).click()
  await page.locator('main').getByRole('link', { name: 'Зарегистрироваться', exact: true }).click()
  await page.getByLabel('Имя', { exact: true }).fill('Новый')
  await page.getByLabel('Фамилия', { exact: true }).fill('Клиент')
  await page.getByLabel('Электронная почта').fill('purchase@forma.demo')
  await page.getByLabel('Пароль', { exact: true }).fill('NewTest123!')
  await page.getByLabel('Повторите пароль').fill('NewTest123!')
  await page.getByRole('button', { name: 'Создать аккаунт', exact: true }).click()
  await expect(page).toHaveURL(/\/cart$/)
  await expect(page.getByRole('button', { name: 'Создать заказ и перейти к оплате' })).toBeDisabled()
  await page.getByRole('button', { name: 'Имитировать подтверждение email' }).click()
  await page.getByRole('button', { name: 'Создать заказ и перейти к оплате' }).click()
  await page.getByRole('button', { name: 'Оплатить в деморежиме' }).click()
  await page.getByRole('link', { name: 'Купленный доступ 1' }).click()
  await expect(page.locator('.access-status-unused')).toHaveText('Не использовано')
  await expect(page.locator('.account-content')).toContainText('Вход не отмечен')
  await expect(page.locator('.zone-badges span')).toHaveCount(2)
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('single-visit-ru.png'), fullPage: true })
  await page.reload()
  await expect(page.getByLabel('Электронная почта')).toBeVisible()
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual([])
})

test('disjoint zones can overlap, combined access conflicts and unpaid order can be cancelled', async ({ page }) => {
  await page.goto('/plans')
  await add(page, 'Абонемент', 'gym')
  await page.getByRole('link', { name: /Выбрать посещение/ }).click()
  await add(page, 'Абонемент', 'pool')
  await signIn(page)
  await page.getByRole('button', { name: 'Создать заказ и перейти к оплате' }).click()
  await page.getByRole('button', { name: 'Оплатить в деморежиме' }).click()
  await expect(page.getByRole('link', { name: /Купленный доступ [12]/ })).toHaveCount(2)
  await page.getByRole('link', { name: /^Корзина/ }).click()
  await page.getByRole('link', { name: /Выбрать посещение/ }).click()
  await add(page)
  await expect(page.getByRole('alert')).toContainText('пересекаются в одной зоне')
  await page.getByRole('link', { name: 'Изменить', exact: true }).click()
  await page.getByLabel('Дата начала', { exact: true }).fill('2100-04-05')
  await page.getByRole('button', { name: 'Сохранить изменения' }).click()
  await page.getByRole('button', { name: 'Создать заказ и перейти к оплате' }).click()
  await page.getByRole('button', { name: 'Отменить неоплаченный заказ' }).click()
  await expect(page.getByText('Неоплаченный заказ отменён. Доступ не выдан.')).toBeVisible()
  await expect(page.getByRole('button', { name: 'Оплатить в деморежиме' })).toHaveCount(0)
})

test('gallery arrows overlay photos and wrap in both directions', async ({ page }, testInfo) => {
  await page.goto('/#club')
  const gallery = page.locator('.space-photo')
  const prev = gallery.getByRole('button', { name: 'Предыдущее фото' })
  const next = gallery.getByRole('button', { name: 'Следующее фото' })
  await prev.click()
  await expect(page.getByRole('tab', { name: 'Раздевалки и душевые' })).toHaveAttribute('aria-selected', 'true')
  await next.click()
  await expect(page.getByRole('tab', { name: 'Тренажёрный зал' })).toHaveAttribute('aria-selected', 'true')
  await page.evaluate(() => window.scrollTo(0, 0))
  await page.locator('#club').screenshot({ path: testInfo.outputPath('gallery-arrows.png') })
  const bounds = await gallery.boundingBox()
  for (const button of [prev, next]) {
    const b = await button.boundingBox()
    expect(b!.width).toBeGreaterThanOrEqual(52)
    expect(b!.x).toBeGreaterThan(bounds!.x)
    expect(b!.x + b!.width).toBeLessThan(bounds!.x + bounds!.width)
  }
})
