import { expect, test } from '@playwright/test'

test('membership cards show shared access, total prices and preserve the chosen plan', async ({ page }, testInfo) => {
  await page.goto('/#memberships')
  const memberships = page.locator('#memberships')
  await expect(memberships.getByRole('article')).toHaveCount(3)
  await expect(memberships).toContainText('раздевалки и душевые')
  await expect(memberships).toContainText('120,00')
  await expect(memberships).toContainText('320,00')
  await expect(memberships.getByText('За весь срок', { exact: true })).toHaveCount(3)
  await expect(memberships.getByRole('heading', { name: 'Первое посещение — бесплатно' })).toBeVisible()
  await memberships.screenshot({ path: testInfo.outputPath('membership-cards.png') })
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(memberships.getByRole('heading', { name: 'Your first visit is free' })).toBeVisible()
  await expect(memberships.getByText('Full-term price', { exact: true })).toHaveCount(3)
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
  await memberships.getByRole('link', { name: 'Choose membership: 3 months', exact: true }).click()
  await expect(page).toHaveURL(/\/register\?plan=2$/)
})

test('guest form validates without an account, sends no request and restores trigger focus', async ({ page }, testInfo) => {
  const submissions: string[] = []
  page.on('request', request => { if (request.method() === 'POST') submissions.push(request.url()) })
  await page.goto('/#memberships')
  await page.getByRole('button', { name: 'Оставить заявку', exact: true }).click()
  const form = page.getByRole('form', { name: 'Заявка на гостевой визит', exact: true })
  const name = form.getByLabel('Имя', { exact: true })
  const phone = form.getByLabel('Телефон', { exact: true })
  await expect(name).toBeFocused()
  await form.getByRole('button', { name: 'Проверить заявку', exact: true }).click()
  await expect(name).toHaveAttribute('aria-invalid', 'true')
  await expect(phone).toHaveAttribute('aria-invalid', 'true')
  await expect(name).toBeFocused()
  await name.fill('Тестовый посетитель')
  await phone.fill('not a phone')
  await form.getByRole('button', { name: 'Проверить заявку', exact: true }).click()
  await expect(phone).toHaveAttribute('aria-invalid', 'true')
  await expect(form.getByRole('status')).toHaveCount(0)
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.getByText('Enter a phone number with 7–15 digits.', { exact: false })).toBeVisible()
  const englishForm = page.getByRole('form', { name: 'Guest visit request', exact: true })
  await englishForm.getByLabel('Phone number', { exact: true }).fill('+375 (29) 000-00-00')
  await englishForm.getByRole('button', { name: 'Check request', exact: true }).click()
  await expect(englishForm.getByRole('status')).toContainText('no request was sent and no visit has been booked')
  expect(submissions).toEqual([])
  await englishForm.screenshot({ path: testInfo.outputPath('guest-form.png') })
  await englishForm.getByLabel('Name', { exact: true }).fill('Другой посетитель')
  await expect(englishForm.getByRole('status')).toHaveCount(0)
  await englishForm.getByLabel('Name', { exact: true }).press('Escape')
  await expect(page.getByRole('button', { name: 'Request a visit', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Request a visit', exact: true }).click()
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Phone number', { exact: true })).toHaveValue('')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
})
