import { expect, test } from '@playwright/test'

test('guest form validates without an account, sends no request and restores trigger focus', async ({ page }, testInfo) => {
  const submissions: string[] = []
  page.on('request', request => { if (request.method() === 'POST') submissions.push(request.url()) })
  await page.goto('/#memberships')
  await page.getByRole('button', { name: 'Оставить заявку', exact: true }).click()
  const form = page.getByRole('form', { name: 'Заявка на гостевой визит', exact: true })
  const name = form.getByLabel('Имя', { exact: true })
  const phone = form.getByLabel('Телефон', { exact: true })
  await expect(name).toBeFocused()
  await form.getByRole('button', { name: 'Проверить заявку', exact: true }).click()
  await expect(name).toHaveAttribute('aria-invalid', 'true')
  await expect(phone).toHaveAttribute('aria-invalid', 'true')
  await expect(name).toBeFocused()
  await name.fill('Тестовый посетитель')
  await phone.fill('not a phone')
  await form.getByRole('button', { name: 'Проверить заявку', exact: true }).click()
  await expect(phone).toHaveAttribute('aria-invalid', 'true')
  await expect(form.getByRole('status')).toHaveCount(0)
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.getByText('Enter a phone number with 7–15 digits.', { exact: false })).toBeVisible()
  const englishForm = page.getByRole('form', { name: 'Guest visit request', exact: true })
  await englishForm.getByLabel('Phone number', { exact: true }).fill('+375 (29) 000-00-00')
  await englishForm.getByRole('button', { name: 'Check request', exact: true }).click()
  await expect(englishForm.getByRole('status')).toContainText('no request was sent and no visit has been booked')
  expect(submissions).toEqual([])
  await englishForm.screenshot({ path: testInfo.outputPath('guest-form.png') })
  await englishForm.getByLabel('Name', { exact: true }).fill('Другой посетитель')
  await expect(englishForm.getByRole('status')).toHaveCount(0)
  await englishForm.getByLabel('Name', { exact: true }).press('Escape')
  await expect(page.getByRole('button', { name: 'Request a visit', exact: true })).toBeFocused()
  await page.getByRole('button', { name: 'Request a visit', exact: true }).click()
  await expect(page.getByLabel('Name', { exact: true })).toHaveValue('')
  await expect(page.getByLabel('Phone number', { exact: true })).toHaveValue('')
  expect(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false)
})
