import { expect, test } from '@playwright/test'

test('footer groups contact details and offers working cross-route navigation', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/plans')
  const footer = page.getByRole('contentinfo')
  await expect(footer).toContainText('пр. Независимости, 19')
  await expect(footer).toContainText('07:00–23:00')
  await expect(footer.getByRole('navigation').getByRole('link')).toHaveCount(4)
  await footer.scrollIntoViewIfNeeded()
  await footer.screenshot({ path: testInfo.outputPath('footer-ru.png') })
  await footer.getByRole('link', { name: 'Записаться на первый визит' }).click()
  await expect(page).toHaveURL(/\/#guest-visit$/)
  await expect(page.locator('#guest-visit')).toBeFocused()
  await footer.getByRole('link', { name: 'Наверх', exact: true }).click()
  await expect(page.locator('#main')).toBeFocused()
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.getByRole('button', { name: 'Orange theme', exact: true }).click()
  await expect(footer).toContainText('19 Nezavisimosti Avenue')
  await expect(footer.getByRole('heading', { name: 'Opening hours' })).toBeVisible()
  await page.setViewportSize({ width: 768, height: 900 })
  await footer.scrollIntoViewIfNeeded()
  await footer.screenshot({ path: testInfo.outputPath('footer-en-orange-768.png') })
  await page.setViewportSize({ width: 320, height: 850 })
  await footer.scrollIntoViewIfNeeded()
  await footer.screenshot({ path: testInfo.outputPath('footer-en-orange-320.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await footer.getByRole('link', { name: 'Memberships', exact: true }).click()
  await expect(page).toHaveURL(/\/plans$/)
  await expect(page.locator('h1')).toHaveText('Memberships')
  await expect(page.getByText('Demo mode: no real charges.', { exact: false })).toHaveCount(0)
})
