import { expect, test } from '@playwright/test'

test('hero leads to guest terms and preserves the existing demo form', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Первое посещение бесплатно', exact: true }).click()
  await expect(page).toHaveURL(/#guest-visit$/)
  await expect(page.locator('#guest-visit')).toBeFocused()
  await expect(page.locator('#guest-visit')).toContainText('Занятие с тренером не входит')
  await page.getByRole('button', { name: 'Оставить заявку', exact: true }).click()
  await expect(page.getByLabel('Имя', { exact: true })).toBeFocused()
  await page.getByLabel('Имя', { exact: true }).press('Escape')
  await expect(page.getByRole('button', { name: 'Оставить заявку', exact: true })).toBeFocused()
})

test('gallery supports buttons, keyboard boundaries and language switching', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const gallery = page.getByRole('region', { name: 'Посмотрите клуб', exact: true })
  const track = gallery.getByRole('list', { name: 'Фотогалерея' })
  const count = gallery.locator('[aria-live]')
  await expect(gallery.getByRole('button', { name: 'Предыдущее фото' })).toBeDisabled()
  await gallery.getByRole('button', { name: 'Следующее фото' }).click()
  await expect(count).toContainText('02 / 04')
  await track.focus()
  await page.keyboard.press('ArrowRight')
  await expect(count).toContainText('03 / 04')
  await page.keyboard.press('End')
  await expect(count).toContainText('04 / 04')
  await expect(gallery.getByRole('button', { name: 'Следующее фото' })).toBeDisabled()
  await page.keyboard.press('ArrowRight')
  await expect(count).toContainText('04 / 04')
  await page.keyboard.press('Home')
  await expect(count).toContainText('01 / 04')
  await page.keyboard.press('ArrowLeft')
  await expect(count).toContainText('01 / 04')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  const englishGallery = page.getByRole('region', { name: 'Take a look around' })
  await expect(englishGallery).toBeVisible()
  await page.getByRole('button', { name: 'Next photo', exact: true }).click()
  await expect(englishGallery.locator('[aria-live]')).toContainText('Cardio zone')
  const englishTrack = englishGallery.getByRole('list', { name: 'Photo carousel' })
  await englishTrack.focus()
  await page.keyboard.press('End')
  await page.setViewportSize({ width: 320, height: 850 })
  await expect(englishGallery.locator('[aria-live]')).toContainText('04 / 04')
  await page.keyboard.press('Home')
  await expect(englishGallery.locator('[aria-live]')).toContainText('01 / 04')
  await page.locator('.fp-gallery').screenshot({ path: testInfo.outputPath('gallery-en.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})

test('native touch swipe advances gallery without trapping vertical page scrolling', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'Touch-specific browser interaction')
  await page.goto('/')
  const track = page.locator('.fp-gallery-track')
  await track.scrollIntoViewIfNeeded()
  const bounds = await track.boundingBox()
  const session = await page.context().newCDPSession(page)
  const x = bounds!.x + bounds!.width * .85
  const y = bounds!.y + 130
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  for (let step = 1; step <= 8; step++) {
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - bounds!.width * .78 * step / 8, y }] })
  }
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(page.locator('.fp-gallery-count')).toContainText('02 / 04')
  const before = await page.evaluate(() => scrollY)
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x - 100, y: y + 90 }] })
  for (let step = 1; step <= 8; step++) {
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 100, y: y + 90 - step * 15 }] })
  }
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(before + 30)
  await session.detach()
})

test('homepage coaches match the catalogue and all new images load', async ({ page }, testInfo) => {
  await page.goto('/')
  const coaches = page.locator('.fp-coaches')
  await expect(coaches.getByRole('article')).toHaveCount(3)
  await expect(coaches).toContainText('Учебные профили')
  await expect(coaches.getByRole('heading', { name: 'Михаил Соколов' })).toBeVisible()
  for (const image of await page.locator('.fp-hero img, .fp-activity img, .trainer-portrait img').all()) {
    await image.scrollIntoViewIfNeeded()
    await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
  }
  await coaches.screenshot({ path: testInfo.outputPath('homepage-coaches.png') })
  await page.locator('.fp-hero').screenshot({ path: testInfo.outputPath('hero.png') })
  await page.locator('.fp-directions').screenshot({ path: testInfo.outputPath('directions.png') })
  const names = await coaches.locator('h3').allTextContents()
  await coaches.getByRole('link', { name: 'Все тренеры' }).click()
  await expect(page).toHaveURL(/\/trainers$/)
  await expect(page.locator('.trainer-profile h2')).toHaveText(names)
})
