import { expect, test } from '@playwright/test'

test('hero leads to separate guest terms and preserves the demo form', async ({ page }) => {
  await page.goto('/')
  await page.getByRole('link', { name: 'Первое посещение бесплатно', exact: true }).click()
  await expect(page).toHaveURL(/#guest-visit$/)
  await expect(page.locator('#guest-visit')).toBeFocused()
  await expect(page.locator('#guest-visit .fp-guest-terms')).toHaveCount(0)
  await expect(page.locator('#memberships #guest-visit')).toHaveCount(0)
  await page.getByRole('button', { name: 'Оставить заявку', exact: true }).click()
  await expect(page.locator('#fp-guest-form')).toContainText('по подтверждению администратора')
  await expect(page.getByLabel('Имя', { exact: true })).toBeFocused()
  await page.getByLabel('Имя', { exact: true }).press('Escape')
  await expect(page.getByRole('button', { name: 'Оставить заявку', exact: true })).toBeFocused()
})

test('space arrows preserve keyboard focus and translated selection', async ({ page }, testInfo) => {
  await page.goto('/#club')
  const spaces = page.locator('#club')
  const next = spaces.locator('.space-arrow').last()
  const selected = spaces.locator('.space-current-title')
  await expect(spaces.locator('.fp-gallery-count')).toHaveCount(0)
  const photo = spaces.locator('.space-photo')
  const height = (await photo.boundingBox())!.height
  await expect(spaces.getByRole('tab')).toHaveCount(0)
  await expect(spaces.getByRole('button', { name: 'Предыдущее фото' })).toBeEnabled()
  await spaces.getByRole('button', { name: 'Следующее фото' }).click()
  await expect(selected).toHaveText('Кардиозона')
  await next.focus()
  await page.keyboard.press('ArrowRight')
  await expect(next).toBeFocused()
  await expect(selected).toHaveText('Бассейн')
  await expect(spaces.locator('.space-copy')).toContainText('Плавание в своём темпе')
  await expect(spaces.getByRole('img')).toHaveAttribute('src', '/images/club/pool-inside.webp')
  await expect(photo.locator('.is-active')).toHaveCSS('opacity', '1')
  await spaces.screenshot({ path: testInfo.outputPath('spaces-pool-inside.png') })
  await spaces.getByRole('button', { name: 'На улице', exact: true }).click()
  await expect(spaces.getByRole('button', { name: 'На улице', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(spaces.getByRole('img')).toHaveAttribute('src', '/images/club/pool-outside.webp')
  await expect(spaces.getByRole('img')).toHaveAttribute('alt', /Открытый бассейн/)
  expect((await photo.boundingBox())!.height).toBe(height)
  await expect(photo.locator('.is-active')).toHaveCSS('opacity', '1')
  await expect(spaces.locator('.space-copy-slide.is-active')).toHaveCSS('opacity', '1')
  await spaces.screenshot({ path: testInfo.outputPath('spaces-pool.png') })
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(selected).toHaveText('Pool')
  await expect(spaces.getByRole('button', { name: 'Outdoors', exact: true })).toHaveAttribute('aria-pressed', 'true')
  await expect(spaces.getByRole('img')).toHaveAttribute('alt', /outdoor pool/)
  await spaces.getByRole('button', { name: 'Indoors', exact: true }).click()
  await expect(spaces.getByRole('img')).toHaveAttribute('src', '/images/club/pool-inside.webp')
  await next.focus()
  await page.keyboard.press('End')
  await expect(next).toBeFocused()
  await expect(selected).toHaveText('Changing rooms')
  await expect(spaces.getByRole('button', { name: 'Next photo' })).toBeEnabled()
  await expect(spaces.locator('.space-copy')).toContainText('Included with every visit')
  await page.keyboard.press('ArrowRight')
  await expect(next).toBeFocused()
  await expect(selected).toHaveText('Gym floor')
  await page.keyboard.press('ArrowLeft')
  await expect(next).toBeFocused()
  await expect(selected).toHaveText('Changing rooms')
  await page.keyboard.press('Home')
  await expect(next).toBeFocused()
  await expect(selected).toHaveText('Gym floor')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await next.press('ArrowRight')
  await next.press('ArrowRight')
  const duration = await photo.locator('.is-active').evaluate(el => getComputedStyle(el).animationDuration)
  expect(parseFloat(duration)).toBeLessThan(.01)
  await page.setViewportSize({ width: 320, height: 850 })
  await expect(spaces.locator('.space-copy-slide.is-active')).toHaveCSS('opacity', '1')
  await expect(spaces.locator('.space-copy-slide.is-active')).toHaveCSS('transition-delay', '0s')
  await spaces.screenshot({ path: testInfo.outputPath('spaces-en-320.png') })
  await spaces.getByRole('button', { name: 'Outdoors', exact: true }).click()
  await expect(spaces.getByRole('img')).toHaveAttribute('src', '/images/club/pool-outside.webp')
  await spaces.screenshot({ path: testInfo.outputPath('spaces-outside-en-320.png') })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await spaces.getByRole('link', { name: 'Choose membership' }).click()
  await expect(page.locator('#memberships')).toBeFocused()
})

test('native touch swipe changes spaces without trapping vertical page scrolling', async ({ page }, testInfo) => {
  test.skip(testInfo.project.name !== 'mobile', 'Touch-specific browser interaction')
  await page.goto('/')
  const photo = page.locator('.space-photo')
  await photo.scrollIntoViewIfNeeded()
  const bounds = await photo.boundingBox()
  const session = await page.context().newCDPSession(page)
  const x = bounds!.x + bounds!.width * .85
  const y = bounds!.y + bounds!.height / 2
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x, y }] })
  for (let step = 1; step <= 8; step++) {
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - bounds!.width * .7 * step / 8, y }] })
  }
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect(page.locator('.space-current-title')).toHaveText('Кардиозона')
  const before = await page.evaluate(() => scrollY)
  await session.send('Input.dispatchTouchEvent', { type: 'touchStart', touchPoints: [{ x: x - 100, y: y + 40 }] })
  for (let step = 1; step <= 8; step++) {
    await session.send('Input.dispatchTouchEvent', { type: 'touchMove', touchPoints: [{ x: x - 100, y: y + 40 - step * 15 }] })
  }
  await session.send('Input.dispatchTouchEvent', { type: 'touchEnd', touchPoints: [] })
  await expect.poll(() => page.evaluate(() => scrollY)).toBeGreaterThan(before + 30)
  await expect(page.locator('.space-current-title')).toHaveText('Кардиозона')
  await session.detach()
})

test('homepage coaches match the catalogue and local images load', async ({ page }, testInfo) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  const coaches = page.locator('.fp-coaches')
  await expect(coaches.getByRole('article')).toHaveCount(3)
  await expect(coaches.locator('.trainer-demo-note, .trainer-number')).toHaveCount(0)
  await expect(page.locator('.hero-eyebrow, .hero-caption, .section-index')).toHaveCount(0)
  await expect(coaches.getByRole('heading', { name: 'Максим Савицкий' })).toBeVisible()
  await expect(coaches.locator('.trainer-bio, .trainer-education, .trainer-experience')).toHaveCount(0)
  for (const image of await page.locator('.fp-hero img, .space-photo .space-layer, .trainer-portrait img').all()) {
    await image.scrollIntoViewIfNeeded()
    await expect.poll(() => image.evaluate((img: HTMLImageElement) => img.complete && img.naturalWidth > 0)).toBe(true)
  }
  await coaches.screenshot({ path: testInfo.outputPath('homepage-coaches.png') })
  await page.evaluate(() => { (document.activeElement as HTMLElement)?.blur(); window.scrollTo({ top: 0, behavior: 'instant' }) })
  await page.screenshot({ path: testInfo.outputPath('hero.png'), scale: 'css' })
  await page.screenshot({ path: testInfo.outputPath('homepage.png'), fullPage: true, scale: 'css' })
  const names = await coaches.locator('h3').allTextContents()
  await coaches.getByRole('link', { name: 'Все тренеры' }).click()
  await expect(page).toHaveURL(/\/trainers$/)
  await expect(page.locator('.trainer-profile h2')).toHaveText(names)
  await expect(page.locator('.trainer-bio')).toHaveCount(3)
  await expect(page.locator('.trainer-demo-note')).toHaveCount(0)
  await expect(page.locator('.trainer-education')).toHaveCount(3)
  await expect(page.locator('.trainer-education')).toContainText(['Университет Лафборо', 'Белорусский государственный университет', 'Немецкий спортивный университет Кёльна'])
  await expect(page.getByRole('link', { name: 'Расписание тренера' })).toHaveCount(3)
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.locator('.trainer-profile h2')).toHaveText(['Daniel Moreau', 'Sofia Koval', 'Maksim Savitski'])
  await expect(page.locator('.trainer-education')).toContainText(['Loughborough University', 'Belarusian State University', 'German Sport University Cologne'])
})

test('FAQ supports quick reversal, keyboard closing and reduced motion', async ({ page }, testInfo) => {
  await page.goto('/')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  const faq = page.locator('.fp-faqs details').first()
  const question = faq.locator('summary')
  await question.focus()
  await page.keyboard.press('Enter')
  await expect(question).toHaveAttribute('aria-expanded', 'true')
  await page.keyboard.press('Enter')
  await page.keyboard.press('Enter')
  await expect.poll(() => faq.evaluate(element => element.getAnimations().length)).toBe(0)
  await expect(faq).toHaveAttribute('open', '')
  await page.setViewportSize({ width: 320, height: 850 })
  await expect(faq.locator('.fp-disclosure-content')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.locator('.fp-visiting').screenshot({ path: testInfo.outputPath('faq-open.png') })
  await question.press('Space')
  await expect(faq).not.toHaveAttribute('open', '')
  await expect(question).toBeFocused()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await question.press('Enter')
  await expect(faq).toHaveAttribute('open', '')
  expect(await faq.evaluate(element => element.getAnimations().length)).toBe(0)
  await question.press('Enter')
  await expect(faq).not.toHaveAttribute('open', '')
  await expect(page.locator('.trainer-demo-note')).toHaveCount(0)
})
