import { expect, test } from '@playwright/test'

test('home anchors work across routes, on reload and with keyboard focus', async ({ page }) => {
  await page.goto('/plans')
  async function follow(label: string) {
    const toggle = page.getByRole('button', { name: 'Открыть меню' })
    const mobile = await toggle.isVisible()
    if (mobile) await toggle.click()
    const navigation = page.getByRole('navigation', { name: mobile ? 'Мобильная навигация' : 'Основная навигация' })
    await navigation.getByRole('link', { name: label, exact: true }).focus()
    await page.keyboard.press('Enter')
  }
  await follow('О клубе')
  await expect(page).toHaveURL(/\/#club$/)
  await expect(page.locator('#club')).toBeFocused()
  await expect(page.getByRole('button', { name: 'Тренажёрный зал', exact: true })).toHaveAttribute('aria-expanded', 'true')
  const pool = page.getByRole('button', { name: 'Водные программы', exact: true })
  await pool.focus()
  await page.keyboard.press('Enter')
  await expect(pool).toHaveAttribute('aria-expanded', 'true')
  await expect(page.locator('#facility-panel-pool')).toBeVisible()
  await follow('Контакты')
  await expect(page.locator('#contacts')).toBeFocused()
  const rect = await page.locator('#contacts').boundingBox()
  const header = await page.locator('header').boundingBox()
  expect(rect!.y).toBeGreaterThanOrEqual(header!.height)
  await page.goBack()
  await expect(page.locator('#club')).toBeFocused()
  await page.reload()
  await expect(page.locator('#club')).toBeFocused()
  await follow('О клубе')
  await expect(page.locator('#club')).toBeFocused()
  const question = page.locator('summary').first()
  await question.focus()
  await page.keyboard.press('Enter')
  await expect(page.locator('details').first()).toHaveAttribute('open', '')
})

test('the former preview route shares navigation, typography and page content', async ({ page }) => {
  await page.goto('/design-preview#memberships')
  await expect(page.locator('h1')).toHaveText('Фитнес-клуб FORMA')
  await expect(page.locator('#memberships')).toBeFocused()
  await expect(page.getByRole('banner')).toHaveCount(1)
  await expect(page.getByRole('main')).toHaveCount(1)
  await expect(page.getByRole('contentinfo')).toHaveCount(1)
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.locator('h1')).toHaveText('FORMA fitness club')
  await page.locator('footer').getByRole('link', { name: 'Memberships', exact: true }).click()
  await expect(page).toHaveURL(/\/plans$/)
  await expect(page.locator('h1')).toHaveText('Memberships')
})
