import { expect, test } from '@playwright/test'

test('preview compares full catalogue prices, validates choices before adding to cart', async ({ page }, testInfo) => {
  const writes: string[] = []
  page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()) })
  await page.goto('/plans')
  const preview = page.locator('.offer-preview')
  const total = preview.locator('.offer-total')
  const gym = preview.getByRole('checkbox', { name: /Зал \+ кардио/ })
  const pool = preview.getByRole('checkbox', { name: /Бассейн/ })
  await expect(total).toContainText('320,00')
  await gym.uncheck()
  await expect(total).toContainText('240,00')
  await preview.getByRole('radio', { name: '12 месяцев', exact: true }).check()
  await expect(total).toContainText('840,00')
  await preview.getByRole('radio', { name: '1 месяц', exact: true }).check()
  await expect(total).toContainText('90,00')
  await pool.uncheck()
  await expect(preview.getByRole('alert')).toHaveText('Выберите хотя бы одну зону.')
  await expect(total).toHaveText('—')
  await gym.check()
  await expect(total).toContainText('80,00')
  await pool.check()
  await expect(total).toContainText('120,00')
  await preview.getByLabel('Дата начала', { exact: true }).fill('2099-04-05')
  await preview.getByRole('radio', { name: 'Разовое посещение', exact: true }).check()
  await expect(preview.getByRole('radio', { name: '1 месяц', exact: true })).toHaveCount(0)
  await expect(total).toContainText('28,00')
  await gym.uncheck()
  await expect(total).toContainText('20,00')
  await gym.check()
  await pool.uncheck()
  await expect(total).toContainText('15,00')
  await expect(preview).toContainText('повторный вход не предусмотрен')
  await preview.locator('.offer-details summary').click()
  await expect(preview.locator('.offer-details')).toHaveAttribute('open', '')
  await expect(preview).toContainText('не даёт права на запись к тренеру')
  await preview.getByLabel('Дата посещения', { exact: true }).fill('2000-01-01')
  await expect(preview.getByRole('alert')).toHaveText('Укажите сегодняшнюю или будущую дату.')
  await expect(preview.getByLabel('Дата посещения', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await preview.getByLabel('Дата посещения', { exact: true }).fill('2099-05-06')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(preview.getByRole('radio', { name: 'Single visit', exact: true })).toBeChecked()
  await expect(preview.getByLabel('Visit date', { exact: true })).toHaveValue('2099-05-06')
  await expect(preview.getByRole('button', { name: 'Add to cart' })).toBeEnabled()
  await preview.getByRole('radio', { name: 'Membership', exact: true }).check()
  await expect(preview.getByLabel('Start date', { exact: true })).toHaveValue('2099-04-05')
  await preview.screenshot({ path: testInfo.outputPath('offer-en.png') })
  expect(writes).toEqual([])
  await page.reload()
  await expect(preview.getByRole('checkbox', { name: /Pool/ })).toBeChecked()
  await expect(preview.getByRole('radio', { name: '3 months', exact: true })).toBeChecked()
  await expect(preview.getByLabel('Start date', { exact: true })).not.toHaveValue('2099-04-05')
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual(['northside.language'])
})

test('compact home picker carries every selection to plans and supports keyboard, RU/EN and 320px', async ({ page }, testInfo) => {
  await page.goto('/#memberships')
  const picker = page.locator('.visit-picker')
  await expect(page.locator('.offer-preview')).toHaveCount(0)
  await expect(picker.locator('input[type="date"], .offer-total, button')).toHaveCount(0)
  await picker.getByRole('radio', { name: 'Абонемент', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(picker.getByRole('radio', { name: 'Разовое посещение', exact: true })).toBeChecked()
  await picker.getByRole('radio', { name: 'Зал + кардио', exact: true }).focus()
  await page.keyboard.press('ArrowRight')
  await expect(picker.getByRole('radio', { name: 'Бассейн', exact: true })).toBeChecked()
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(picker.getByRole('radio', { name: 'Single visit', exact: true })).toBeChecked()
  await expect(picker.getByRole('radio', { name: 'Pool', exact: true })).toBeChecked()
  await page.setViewportSize({ width: 320, height: 850 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await picker.screenshot({ path: testInfo.outputPath('home-picker-en-320.png') })
  await picker.getByRole('link', { name: 'Continue selection', exact: true }).click()
  await expect(page).toHaveURL(/\/plans\?format=single_visit&zones=pool$/)
  const preview = page.locator('.offer-preview')
  await expect(preview.getByRole('radio', { name: 'Single visit', exact: true })).toBeChecked()
  await expect(preview.getByRole('checkbox', { name: /Gym \+ cardio/ })).not.toBeChecked()
  await expect(preview.getByRole('checkbox', { name: /Pool/ })).toBeChecked()
  await expect(preview.locator('.offer-total')).toContainText('20.00')
  await expect(page.locator('.commerce-intro')).toHaveCount(0)
  await expect(preview.getByLabel('Visit date', { exact: true })).not.toHaveValue('')
  await preview.getByLabel('Visit date', { exact: true }).fill('')
  await expect(preview.getByRole('alert')).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await preview.screenshot({ path: testInfo.outputPath('plans-offer-en-320.png') })

  await page.getByRole('button', { name: 'RU', exact: true }).click()
  for (const format of ['membership', 'single_visit']) {
    for (const zones of ['gym', 'pool', 'both']) {
      await page.goto('/#memberships')
      await picker.getByRole('radio', { name: format === 'membership' ? 'Абонемент' : 'Разовое посещение', exact: true }).check()
      await picker.getByRole('radio', { name: { gym: 'Зал + кардио', pool: 'Бассейн', both: 'Всё вместе' }[zones]!, exact: true }).check()
      await picker.getByRole('link', { name: 'Продолжить выбор', exact: true }).click()
      await expect(page).toHaveURL('/plans?format=' + format + '&zones=' + zones)
      await expect(preview.getByRole('radio', { name: format === 'membership' ? 'Абонемент' : 'Разовое посещение', exact: true })).toBeChecked()
      expect(await preview.getByRole('checkbox', { name: /Зал \+ кардио/ }).isChecked()).toBe(zones !== 'pool')
      expect(await preview.getByRole('checkbox', { name: /Бассейн/ }).isChecked()).toBe(zones !== 'gym')
      if (format === 'membership') await expect(preview.getByRole('radio', { name: '3 месяца', exact: true })).toBeChecked()
      await expect(page.locator('header a[href="/cart"]')).toHaveAccessibleName('Корзина')
    }
  }
})
