import { expect, test } from '@playwright/test'

test('preview compares full catalogue prices, validates choices before adding to cart', async ({ page }, testInfo) => {
  const writes: string[] = []
  page.on('request', request => { if (request.method() !== 'GET') writes.push(request.url()) })
  await page.goto('/plans')
  const preview = page.locator('.offer-preview')
  const total = preview.locator('.offer-total')
  const gym = preview.getByRole('checkbox', { name: /Зал \+ кардио/ })
  const pool = preview.getByRole('checkbox', { name: /Бассейн/ })
  await expect(total).toContainText('320,00')
  await gym.uncheck()
  await expect(total).toContainText('240,00')
  await preview.getByRole('radio', { name: '12 месяцев', exact: true }).check()
  await expect(total).toContainText('840,00')
  await preview.getByRole('radio', { name: '1 месяц', exact: true }).check()
  await expect(total).toContainText('90,00')
  await pool.uncheck()
  await expect(preview.getByRole('alert')).toHaveText('Выберите хотя бы одну зону.')
  await expect(total).toHaveText('—')
  await gym.check()
  await expect(total).toContainText('80,00')
  await pool.check()
  await expect(total).toContainText('120,00')
  await preview.getByLabel('Дата начала', { exact: true }).fill('2099-04-05')
  await preview.getByRole('radio', { name: 'Разовое посещение', exact: true }).check()
  await expect(preview.getByRole('radio', { name: '1 месяц', exact: true })).toHaveCount(0)
  await expect(total).toContainText('28,00')
  await gym.uncheck()
  await expect(total).toContainText('20,00')
  await gym.check()
  await pool.uncheck()
  await expect(total).toContainText('15,00')
  await expect(preview).toContainText('После выхода повторный вход')
  await expect(preview).toContainText('не даёт права на запись к тренеру')
  await preview.getByLabel('Дата посещения', { exact: true }).fill('2000-01-01')
  await expect(preview.getByRole('alert')).toHaveText('Укажите сегодняшнюю или будущую дату.')
  await expect(preview.getByLabel('Дата посещения', { exact: true })).toHaveAttribute('aria-invalid', 'true')
  await preview.getByLabel('Дата посещения', { exact: true }).fill('2099-05-06')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(preview.getByRole('radio', { name: 'Single visit', exact: true })).toBeChecked()
  await expect(preview.getByLabel('Visit date', { exact: true })).toHaveValue('2099-05-06')
  await expect(preview.getByRole('button', { name: 'Add to cart' })).toBeEnabled()
  await preview.getByRole('radio', { name: 'Membership', exact: true }).check()
  await expect(preview.getByLabel('Start date', { exact: true })).toHaveValue('2099-04-05')
  await preview.screenshot({ path: testInfo.outputPath('offer-en.png') })
  expect(writes).toEqual([])
  await page.reload()
  await expect(preview.getByRole('checkbox', { name: /Pool/ })).toBeChecked()
  await expect(preview.getByRole('radio', { name: '3 months', exact: true })).toBeChecked()
  await expect(preview.getByLabel('Start date', { exact: true })).not.toHaveValue('2099-04-05')
  expect(await page.evaluate(() => Object.keys(localStorage))).toEqual(['forma.language'])
})

test('shared offer is keyboard accessible on home and plans with no dead navigation', async ({ page }, testInfo) => {
  for (const route of ['/', '/plans']) {
    await page.goto(route)
    const preview = page.locator('.offer-preview')
    await expect(preview.locator('.offer-total')).toContainText('320,00')
    const membership = preview.getByRole('radio', { name: 'Абонемент', exact: true })
    await membership.focus()
    await page.keyboard.press('ArrowRight')
    await expect(preview.getByRole('radio', { name: 'Разовое посещение', exact: true })).toBeChecked()
    await page.keyboard.press('Tab')
    const gym = preview.getByRole('checkbox', { name: /Зал \+ кардио/ })
    await expect(gym).toBeFocused()
    await page.keyboard.press('Space')
    await expect(preview.locator('.offer-total')).toContainText('20,00')
    await preview.getByLabel('Дата посещения', { exact: true }).fill('')
    await expect(preview.getByRole('alert')).toBeVisible()
    await page.setViewportSize({ width: 320, height: 850 })
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await preview.screenshot({ path: testInfo.outputPath(route === '/' ? 'home-offer-320.png' : 'plans-offer-320.png') })
    await expect(page.locator('a[href="/cart"]')).toBeVisible()
    await expect(page.locator('a[href^="/schedule"]')).toHaveCount(0)
    await expect(preview.getByRole('link')).toHaveCount(0)
  }
})
