import { expect, test } from '@playwright/test'

test('space progress shares the slide clock and preserves pauses', async ({ page }, testInfo) => {
  await page.goto('/')
  const spaces = page.locator('#club')
  const selected = spaces.locator('[role="tab"][aria-selected="true"]')
  const track = spaces.locator('[aria-selected="true"] .space-track > span')
  const state = () => track.evaluate(el => el.getAnimations()[0]?.playState)
  await spaces.scrollIntoViewIfNeeded()
  await page.mouse.move(0, 0)
  await expect.poll(state).toBe('running')
  await track.evaluate(el => { el.getAnimations()[0].currentTime = 7900 })
  await expect(selected).toHaveText('Кардиозона')
  await expect(spaces.getByRole('heading', { name: 'Кардиозона' })).toBeVisible()
  if (testInfo.project.name === 'desktop') {
    await spaces.locator('.space-copy').hover()
    await expect.poll(state).toBe('paused')
    const time = await track.evaluate(el => el.getAnimations()[0].currentTime)
    await page.waitForTimeout(150)
    expect(await track.evaluate(el => el.getAnimations()[0].currentTime)).toBe(time)
    await page.mouse.move(0, 0)
    await expect.poll(state).toBe('running')
  }
  await spaces.getByRole('tab', { name: 'Бассейн', exact: true }).click()
  await page.mouse.move(0, 0)
  await expect.poll(state).toBe('paused')
  await expect(spaces.getByRole('button', { name: 'Продолжить смену фотографий' })).toBeVisible()
  await spaces.getByRole('button', { name: 'Продолжить смену фотографий' }).click()
  await page.mouse.move(0, 0)
  await expect.poll(state).toBe('running')
  await page.evaluate(() => window.scrollTo({ top: document.body.scrollHeight, behavior: 'instant' }))
  await expect.poll(state).toBe('paused')
  await spaces.scrollIntoViewIfNeeded()
  await expect.poll(state).toBe('running')
  await spaces.getByRole('tab', { name: 'Бассейн', exact: true }).focus()
  await expect.poll(state).toBe('paused')
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(spaces.locator('.space-autoplay')).toBeDisabled()
  await spaces.screenshot({ path: testInfo.outputPath('spaces-navigation.png') })
})

test('visit selection precedes coaches and all four zones remain visible at 320px', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  expect(await page.locator('#memberships').evaluate(el => !!(el.compareDocumentPosition(document.querySelector('.fp-coaches')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
  await page.setViewportSize({ width: 320, height: 850 })
  const tabs = page.locator('#club').getByRole('tab')
  await tabs.first().scrollIntoViewIfNeeded()
  for (const tab of await tabs.all()) await expect(tab).toBeVisible()
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
})
