import { expect, test } from '@playwright/test'

test('photo dissolves preserve the visible composition during rapid navigation', async ({ page }, testInfo) => {
  await page.goto('/#club')
  const spaces = page.locator('#club')
  const photo = spaces.locator('.space-photo')
  const next = spaces.getByRole('button', { name: 'Следующее фото' })
  await expect(photo.locator('.is-active')).toHaveCSS('opacity', '1')
  await spaces.getByRole('button', { name: 'Приостановить смену фотографий' }).click()
  await next.click()
  const incoming = photo.locator('.is-active')
  await expect.poll(() => incoming.evaluate(el => el.getAnimations().length)).toBe(1)
  await incoming.evaluate(el => { const animation = el.getAnimations()[0]; animation.pause(); animation.currentTime = 550 })
  await expect.poll(() => incoming.evaluate(el => Number(getComputedStyle(el).opacity))).toBeGreaterThan(.1)
  const opacity = await incoming.evaluate(el => Number(getComputedStyle(el).opacity))
  expect(opacity).toBeLessThan(.9)
  await expect(photo.locator('.space-layer').first()).toHaveCSS('opacity', '1')
  expect(await incoming.evaluate(el => el.getAnimations()[0].effect?.getTiming().duration)).toBe(1100)
  await next.click()
  await expect(photo.locator('.space-layer')).toHaveCount(3)
  expect(await photo.locator('.space-layer').nth(1).evaluate(el => Number(getComputedStyle(el).opacity))).toBeCloseTo(opacity, 3)
  await expect.poll(() => incoming.evaluate(el => el.getAnimations().length)).toBe(1)
  await incoming.evaluate(el => { const animation = el.getAnimations()[0]; animation.currentTime = 1000; animation.play() })
  await expect(photo.locator('.space-layer')).toHaveCount(1)
  await expect(incoming).toHaveCSS('opacity', '1')
  await expect.poll(() => incoming.evaluate(el => el.getAnimations().length)).toBe(0)
  await expect(incoming).toHaveAttribute('src', '/images/club/pool-inside.webp')
  await expect(spaces.locator('.space-copy-slide.is-active')).toHaveCSS('opacity', '1')
  await spaces.locator('.space-clock').evaluate(el => { el.getAnimations()[0].currentTime = 5100 })
  await spaces.screenshot({ path: testInfo.outputPath('gallery-dissolve.png') })
})

test('hero uses an icon control with a translated accessible name', async ({ page }, testInfo) => {
  await page.goto('/')
  const control = page.locator('.hero-playback')
  await expect(control).toHaveText('')
  await expect(control).toHaveAttribute('aria-label', 'Пауза видео')
  await expect(control).toHaveCSS('border-width', '0px')
  const bounds = (await control.boundingBox())!
  expect(bounds.width).toBeGreaterThanOrEqual(44)
  expect(bounds.height).toBeGreaterThanOrEqual(44)
  await control.click()
  await expect(control).toHaveAttribute('aria-label', 'Включить видео')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(control).toHaveAttribute('aria-label', 'Play video')
  await page.locator('.fp-hero').screenshot({ path: testInfo.outputPath('hero-icon.png') })
})
