import { expect, test } from '@playwright/test'

test('spaces show elapsed progress, keep pointer navigation running and preserve intentional pauses', async ({ page }, testInfo) => {
  await page.goto('/#club')
  const spaces = page.locator('#club')
  const selected = spaces.locator('.space-current-title')
  const track = spaces.locator('.space-clock')
  const next = spaces.getByRole('button', { name: 'Следующее фото' })
  const state = () => track.evaluate(el => el.getAnimations()[0]?.playState)
  await expect(spaces).toBeFocused()
  await expect.poll(state).toBe('running')
  await expect(spaces.locator('.space-track')).toBeVisible()
  await track.evaluate(el => { el.getAnimations()[0].currentTime = 9000 })
  await expect(selected).toHaveText('Кардиозона')
  if (testInfo.project.name === 'desktop') {
    for (const target of [selected, spaces.locator('.space-copy'), spaces.locator('.space-photo'), next]) {
      await target.hover()
      await expect.poll(state).toBe('running')
    }
  }
  await next.click()
  await expect(selected).toHaveText('Бассейн')
  await expect.poll(state).toBe('running')
  await expect.poll(() => track.evaluate(el => Number(el.getAnimations()[0]?.currentTime))).toBeLessThan(2000)
  await spaces.getByRole('button', { name: 'На улице', exact: true }).click()
  await expect.poll(state).toBe('running')
  await track.evaluate(el => { el.getAnimations()[0].currentTime = 5100 })
  await spaces.getByRole('button', { name: 'Приостановить смену фотографий' }).click()
  await expect.poll(state).toBe('paused')
  const frozen = await track.evaluate(el => getComputedStyle(el).transform)
  await page.waitForTimeout(150)
  expect(await track.evaluate(el => getComputedStyle(el).transform)).toBe(frozen)
  await next.click()
  await expect(selected).toHaveText('Раздевалки')
  await expect.poll(state).toBe('paused')
  await spaces.getByRole('button', { name: 'Продолжить смену фотографий' }).click()
  await expect.poll(state).toBe('running')
  await page.evaluate(() => window.scrollTo({ top: document.body.scrollHeight, behavior: 'instant' }))
  await expect.poll(state).toBe('paused')
  await spaces.scrollIntoViewIfNeeded()
  await expect.poll(state).toBe('running')
  await spaces.locator('.space-copy').focus()
  await expect.poll(state).toBe('paused')
  await next.focus()
  await next.press('Home')
  await expect(selected).toHaveText('Тренажёрный зал')
  await expect(next).toBeFocused()
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await expect(spaces.locator('.space-autoplay')).toBeDisabled()
  await spaces.screenshot({ path: testInfo.outputPath('spaces-navigation.png') })
})

test('visit selection precedes coaches and all zones remain reachable at 320px', async ({ page }) => {
  await page.emulateMedia({ reducedMotion: 'reduce' })
  await page.goto('/')
  expect(await page.locator('#memberships').evaluate(el => !!(el.compareDocumentPosition(document.querySelector('.fp-coaches')!) & Node.DOCUMENT_POSITION_FOLLOWING))).toBe(true)
  await page.setViewportSize({ width: 320, height: 850 })
  const spaces = page.locator('#club')
  const next = spaces.getByRole('button', { name: 'Следующее фото' })
  await spaces.scrollIntoViewIfNeeded()
  for (const name of ['Тренажёрный зал', 'Кардиозона', 'Бассейн', 'Раздевалки', 'Тренажёрный зал']) {
    await expect(spaces.locator('.space-current-title')).toHaveText(name)
    await expect(next).toBeVisible()
    expect((await next.boundingBox())!.width).toBeGreaterThanOrEqual(44)
    expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
    await next.click()
  }
})
