import { expect, test, type Page } from '@playwright/test'
test.beforeEach(async ({ page }) => { await page.clock.setFixedTime(new Date('2026-10-03T09:00:00Z')) })

async function login(page: Page) {
  await page.getByRole('button', { name: 'Заполнить демоданные' }).click()
  await page.getByRole('button', { name: 'Войти в аккаунт' }).click()
}
async function nav(page: Page, label: string) {
  const menu = page.getByRole('button', { name: 'Открыть меню' })
  if (await menu.isVisible()) await menu.click()
  await page.locator('header').getByRole('link', { name: label, exact: true }).filter({ visible: true }).first().click()
}
async function account(page: Page, label: string) { await page.getByRole('navigation', { name: 'Разделы кабинета' }).getByRole('link', { name: new RegExp('^' + label) }).click() }

test('guest slot survives sign-in; approval, notifications, cancellation and rejection stay synchronized', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', e => errors.push(e.message))
  await page.goto('/schedule/12')
  await page.getByRole('link', { name: 'Войти для записи', exact: true }).click()
  await login(page)
  await expect(page).toHaveURL(/\/schedule\/12$/)
  await expect(page.getByText('Ваш абонемент подходит. Можно отправить заявку.')).toBeVisible()
  await page.getByRole('button', { name: 'Отправить заявку' }).click()
  await expect(page.locator('.booking-state')).toContainText('Ожидает решения')
  await page.getByRole('button', { name: 'Имитировать одобрение' }).click()
  await expect(page.locator('.booking-state')).toContainText('Подтверждена')
  await account(page, 'Уведомления')
  const note = page.locator('.notification-card').first()
  await note.getByRole('button', { name: 'Отметить прочитанным' }).click()
  await expect(note.locator('.status-badge')).toHaveText('Прочитано')
  await note.getByRole('link', { name: 'Открыть запись' }).click()
  await page.getByLabel('Причина отмены', { exact: true }).fill('Изменились планы')
  await page.getByRole('button', { name: 'Отменить запись', exact: true }).click()
  await expect(page.locator('.booking-state')).toContainText('Отменена')
  await nav(page, 'Расписание')
  await page.getByRole('combobox', { name: 'Зона', exact: true }).selectOption('pool')
  const slot = page.locator('.schedule-list article').filter({ has: page.getByRole('heading', { name: 'Аквааэробика', exact: true }) }).first()
  await expect(slot).toContainText('Свободно мест: 6 / 6')
  await slot.getByRole('link', { name: 'Открыть занятие' }).click()
  await page.getByRole('button', { name: 'Отправить заявку' }).click()
  await page.getByRole('button', { name: 'Имитировать отказ' }).click()
  await expect(page.locator('.booking-state')).toContainText('Отклонена')
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await expect(page.locator('.booking-state')).toContainText('Rejected')
  await page.evaluate(() => scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('booking-en.png'), fullPage: true })
  expect(errors).toEqual([])
})

test('new client purchases pool membership, books eligible session and can repeat or renew access', async ({ page }) => {
  await page.goto('/schedule/12')
  await page.getByRole('link', { name: 'Войти для записи' }).click()
  await page.locator('main').getByRole('link', { name: 'Зарегистрироваться', exact: true }).click()
  await page.getByLabel('Имя', { exact: true }).fill('Новый')
  await page.getByLabel('Фамилия', { exact: true }).fill('Клиент')
  await page.getByLabel('Электронная почта').fill('training@forma.demo')
  await page.getByLabel('Пароль', { exact: true }).fill('NewTest123!')
  await page.getByLabel('Повторите пароль').fill('NewTest123!')
  await page.getByRole('button', { name: 'Создать аккаунт', exact: true }).click()
  await expect(page).toHaveURL(/\/schedule\/12$/)
  await page.getByRole('button', { name: 'Имитировать подтверждение email' }).click()
  await expect(page.getByRole('alert')).toContainText('Нужен неотменённый абонемент')
  await page.getByRole('link', { name: 'Выбрать абонемент', exact: false }).click()
  await page.getByRole('checkbox', { name: /Зал \+ кардио/ }).uncheck()
  await page.getByRole('radio', { name: '1 месяц', exact: true }).check()
  await page.getByRole('button', { name: 'Добавить в корзину' }).click()
  await page.getByRole('button', { name: 'Создать заказ и перейти к оплате' }).click()
  await page.getByRole('button', { name: 'Оплатить в деморежиме' }).click()
  await page.getByRole('link', { name: 'Купленный доступ 1' }).click()
  await page.getByRole('link', { name: 'Продлить', exact: false }).click()
  await expect(page.getByRole('checkbox', { name: /Зал \+ кардио/ })).not.toBeChecked()
  await expect(page.getByRole('radio', { name: '1 месяц', exact: true })).toBeChecked()
  await expect(page.locator('.commerce-intro')).toContainText('Дата предложена после окончания')
  await nav(page, 'Расписание')
  await page.getByRole('combobox', { name: 'Зона', exact: true }).selectOption('pool')
  await page.locator('.schedule-list article').filter({ has: page.getByRole('heading', { name: 'Аквааэробика', exact: true }) }).first().getByRole('link', { name: 'Открыть занятие' }).click()
  await page.getByRole('button', { name: 'Отправить заявку' }).click()
  await page.getByRole('button', { name: 'Имитировать одобрение' }).click()
  await account(page, 'Обзор кабинета')
  await expect(page.locator('.booking-card')).toContainText('Аквааэробика')
  await expect(page.locator('.account-metrics')).toContainText('1')
})

test('public filters, coach links, full slots and 320px RU/EN layouts', async ({ page }, testInfo) => {
  await page.goto('/trainers')
  await page.locator('.trainer-profile').last().getByRole('link', { name: 'Расписание' }).click()
  await expect(page).toHaveURL(/\/schedule\?trainer=7$/)
  await expect(page.getByRole('combobox', { name: 'Тренер', exact: true })).toHaveValue('7')
  await expect(page.locator('.schedule-list article')).toHaveCount(4)
  await page.getByRole('combobox', { name: 'Формат', exact: true }).selectOption('individual')
  await expect(page.locator('.schedule-list article')).toHaveCount(1)
  await page.getByLabel('Дата занятия', { exact: true }).fill('2099-01-01')
  await expect(page.getByText('Занятий по этим условиям нет.')).toBeVisible()
  await page.getByRole('button', { name: 'Сбросить фильтры' }).click()
  await expect(page.locator('.schedule-list article').filter({ hasText: 'Мест нет' })).toHaveCount(1)
  await page.getByRole('button', { name: 'EN', exact: true }).click()
  await page.setViewportSize({ width: 320, height: 850 })
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true)
  await page.screenshot({ path: testInfo.outputPath('schedule-en-320.png'), fullPage: true })
})

test('overview, expiry, recovery demo and sign-in return keep private data isolated', async ({ page }, testInfo) => {
  await page.goto('/account')
  await login(page)
  await expect(page.getByRole('heading', { name: 'Обзор кабинета', exact: true })).toBeVisible()
  await page.evaluate(() => scrollTo(0, 0))
  await page.screenshot({ path: testInfo.outputPath('overview-ru.png'), fullPage: true })
  await page.getByRole('button', { name: 'Имитировать завершение сессии' }).click()
  await expect(page.getByText('Демосессия завершена. Войдите снова, чтобы продолжить.')).toBeVisible()
  await expect(page.getByRole('navigation', { name: 'Разделы кабинета' })).toHaveCount(0)
  await page.getByRole('link', { name: 'Забыли пароль?' }).click()
  await page.getByLabel('Электронная почта').fill('client@forma.demo')
  await page.getByRole('button', { name: 'Проверить демосценарий' }).click()
  await expect(page.getByRole('status')).toContainText('Письмо не отправлено, пароль не изменён')
  await page.getByRole('link', { name: 'Вернуться ко входу' }).click()
  await login(page)
  await expect(page.getByRole('heading', { name: 'Обзор кабинета', exact: true })).toBeVisible()
  await account(page, 'Мои тренировки')
  await page.getByRole('button', { name: 'История', exact: true }).click()
  await expect(page.locator('.booking-card')).toContainText(['Завершена · посещено', 'Завершена · неявка', 'Отклонена', 'Отменена'])
})
