export const offerCopy = {
  ru: {
    format: '01 / Формат посещения', membership: 'Абонемент', single_visit: 'Разовое посещение',
    term: '02 / Срок абонемента', zones: 'Зоны клуба', gym: 'Зал + кардио', pool: 'Бассейн', both: 'Зал + кардио и бассейн',
    gymText: 'Силовые и функциональные упражнения, кардиотренировки.', poolText: 'Самостоятельное плавание в часы работы клуба.',
    month1: '1 месяц', month3: '3 месяца', month12: '12 месяцев',
    startDate: 'Дата начала', visitDate: 'Дата посещения', timezone: 'Дата по времени Минска (Europe/Minsk).',
    summary: 'Ваш вариант', draft: 'Предварительный выбор', total: 'За весь срок', visitTotal: 'За одно посещение',
    demo: 'Демонстрационные цены, не публичная оферта.',
    unavailable: 'Оформление пока недоступно', previewNote: 'Можно сравнить варианты. Выбор не сохраняется и не создаёт заказ.',
    included: 'В любом варианте', amenities: 'Раздевалки, шкафчики и душевые — без доплаты.',
    training: 'Доступ в зоны — для самостоятельных занятий. Тренировки с тренером требуют подходящего абонемента и отдельной записи.',
    visitRule: 'Один вход в выбранную дату, в часы работы клуба. После выхода посещение завершено; повторный вход не предусмотрен.',
    visitTraining: 'Разовое посещение не даёт права на запись к тренеру.',
    zoneError: 'Выберите хотя бы одну зону.', dateError: 'Укажите сегодняшнюю или будущую дату.', missing: 'Для этого варианта нет предложения.',
    notChosen: 'Не выбрано', legacy: 'Действующие демоабонементы',
    legacyNote: 'Прежний каталог с доступом во все зоны и указанными форматами тренировок. Ссылка сохраняет только этот тариф при регистрации; предварительный выбор выше не переносится. Покупка не выполняется.',
  },
  en: {
    format: '01 / Visit format', membership: 'Membership', single_visit: 'Single visit',
    term: '02 / Membership term', zones: 'Club zones', gym: 'Gym + cardio', pool: 'Pool', both: 'Gym + cardio and pool',
    gymText: 'Strength and functional exercise, plus cardio training.', poolText: 'Independent swimming during club opening hours.',
    month1: '1 month', month3: '3 months', month12: '12 months',
    startDate: 'Start date', visitDate: 'Visit date', timezone: 'Date in Minsk time (Europe/Minsk).',
    summary: 'Your selection', draft: 'Explore your options', total: 'Full-term price', visitTotal: 'One-visit price',
    demo: 'Illustrative demo prices, not a commercial offer.',
    unavailable: 'Purchasing is not available yet', previewNote: 'Compare the options. Your selection is not saved and does not create an order.',
    included: 'Included with every option', amenities: 'Changing rooms, lockers and showers at no extra charge.',
    training: 'Zone access is for independent exercise. Coached sessions require an eligible membership and a separate booking.',
    visitRule: 'One admission on the selected date during opening hours. Leaving ends the visit; re-entry is not included.',
    visitTraining: 'A single visit does not qualify for coached bookings.',
    zoneError: 'Select at least one zone.', dateError: 'Choose today or a future date.', missing: 'No offer is available for this selection.',
    notChosen: 'Not selected', legacy: 'Existing demo memberships',
    legacyNote: 'The previous catalogue includes all zones and the listed coached formats. The link keeps only that plan through registration; the preview above is not carried over. No purchase is made.',
  },
} as const
