import { useTranslation } from 'react-i18next'

export const commerceCopy = {
  ru: {
    cart: 'Корзина', cartIntro: 'Проверьте зоны и даты. Все посещения оформляются на владельца аккаунта.',
    empty: 'В корзине пока пусто', emptyText: 'Выберите абонемент или разовое посещение, чтобы начать.', browse: 'Выбрать посещение',
    add: 'Добавить в корзину', save: 'Сохранить изменения', edit: 'Изменить', remove: 'Удалить', back: 'Вернуться в корзину',
    loading: 'Подождите…', currency: 'Валюта оплаты', promo: 'Промокод', apply: 'Применить', clearPromo: 'Убрать промокод',
    demoPromo: 'Для проверки: FORMA10 — скидка 10%.', subtotal: 'Стоимость', discount: 'Скидка', total: 'К оплате',
    conversion: 'Демонстрационный курс', baseTotal: 'Сумма в BYN', rateFixed: 'Курс и валюта фиксируются при создании заказа.',
    createOrder: 'Создать заказ и перейти к оплате', signIn: 'Войти для оформления', signInNote: 'Выбор сохранится в корзине при входе или регистрации.',
    demo: 'Деморежим: реальных списаний нет. Корзина, заказы и сессия сбросятся после обновления страницы.',
    updated: 'Цены обновлены. Проверьте сумму перед оформлением.', refresh: 'Обновить цены в корзине',
    verifyTitle: 'Подтверждение email в деморежиме', verifyNote: 'Для заказа нужен подтверждённый email. Кнопка ниже имитирует подтверждение; письмо не отправляется.', verify: 'Имитировать подтверждение email',
    clientOnly: 'Оформление доступно клиентам', clientOnlyText: 'Выйдите из аккаунта тренера или администратора и войдите как клиент.',
    orders: 'Мои заказы', ordersIntro: 'Сохранённые условия покупок и попытки оплаты.', noOrders: 'Заказов пока нет', order: 'Заказ', details: 'Подробнее',
    created: 'Создан', pending: 'Ожидает оплаты', paid: 'Оплачен', cancelled: 'Отменён', cancelledOrder: 'Неоплаченный заказ отменён. Доступ не выдан.',
    review: 'Проверьте заказ', immutable: 'Цены, зоны, сроки, скидка и курс в этом заказе зафиксированы.',
    payment: 'Имитация оплаты', paymentNote: 'Выберите результат тестового платежа. Данные банковской карты не нужны.',
    successChoice: 'Успешная оплата', failureChoice: 'Отказ оплаты', pay: 'Оплатить в деморежиме', retry: 'Повторить оплату',
    cancelOrder: 'Отменить неоплаченный заказ', success: 'Оплата прошла. Доступ появился в кабинете.', failed: 'Оплата не прошла. Доступ не выдан.',
    attempts: 'История попыток оплаты', succeeded: 'Успешно', declined: 'Отказ', access: 'Купленный доступ',
    memberships: 'Абонементы', passes: 'Разовые посещения', noPasses: 'Разовых посещений пока нет.',
    accessIntro: 'Статус доступа и факт прохода в клуб — разные вещи.', unused: 'Не использовано', used: 'Использовано', expired: 'Истекло', active: 'Действует', upcoming: 'Начнётся позже',
    accessDates: 'Период доступа (время Минска)', starts: 'Начало', ends: 'Окончание, не включительно',
    redeemed: 'Первый вход отмечен', noEntry: 'Вход не отмечен. Покупка не означает проход в клуб.', fixture: 'Демонстрационный пример статуса, без связанного заказа.',
    visitRule: 'Один вход в выбранную дату в часы работы 07:00–23:00. После выхода повторный вход не предусмотрен. Неиспользованный пропуск истекает в конце дня.',
    membershipRule: 'Самостоятельные посещения выбранных зон в часы работы клуба. Даты не сдвигаются автоматически.',
    coaching: 'Форматы занятий с тренером', group: 'Групповые', individual: 'Групповые и индивидуальные', independent: 'Только самостоятельные занятия',
    coachingNote: 'Запись к тренеру появится с расписанием; нужна подходящая зона, действующий абонемент и свободное место. Разовый пропуск не подходит.',
    overlap: 'Абонементы могут совпадать по датам только при разных зонах.',
    selectionStep: '1. Выбор', cartStep: '2. Корзина', paymentStep: '3. Оплата', accessStep: '4. Доступ',
    notFound: 'Запись не найдена', notFoundText: 'Проверьте ссылку или откройте список своего аккаунта.',
    errors: {
      zones_required: 'Выберите хотя бы одну зону.', invalid_date: 'Дата должна существовать и быть не раньше сегодняшней по времени Минска.',
      offer_unavailable: 'Этот вариант больше недоступен. Измените выбор или удалите его из корзины.',
      price_changed: 'Цена или условия изменились. Обновите цены и проверьте итог перед оформлением.',
      cart_changed: 'Корзина изменилась. Обновите страницу корзины и проверьте состав.', cart_empty: 'Добавьте посещение в корзину.',
      invalid_promo: 'Промокод не найден, истёк или отключён.', membership_overlap: 'Даты абонементов пересекаются в одной зоне. Измените дату или зоны; проверьте действующие и будущие абонементы в кабинете.',
      unauthorized: 'Сессия завершена. Войдите снова.', forbidden: 'Это действие доступно только клиентам.', verify_email: 'Подтвердите email в деморежиме.',
      payment_declined: 'Выбран тестовый отказ оплаты. Можно повторить с успешным результатом.', order_changed: 'Заказ уже оплачен или отменён.',
      not_found: 'Запись не найдена в вашем аккаунте.', cart_limit: 'В корзине может быть не больше 12 посещений.',
      idempotency_conflict: 'Параметры запроса изменились. Повторите действие.', invalid_request: 'Некорректный запрос.',
      invalid_currency: 'Выберите доступную валюту.', rate_unavailable: 'Курс пока недоступен. Выберите BYN.', unknown: 'Не удалось выполнить действие. Попробуйте ещё раз.',
    },
  },
  en: {
    cart: 'Cart', cartIntro: 'Review zones and dates. All access belongs to the account holder.',
    empty: 'Your cart is empty', emptyText: 'Choose a membership or a single visit to get started.', browse: 'Choose access',
    add: 'Add to cart', save: 'Save changes', edit: 'Edit', remove: 'Remove', back: 'Back to cart',
    loading: 'Please wait…', currency: 'Payment currency', promo: 'Promo code', apply: 'Apply', clearPromo: 'Remove promo code',
    demoPromo: 'Try FORMA10 for a 10% demo discount.', subtotal: 'Subtotal', discount: 'Discount', total: 'Total to pay',
    conversion: 'Illustrative exchange rate', baseTotal: 'BYN total', rateFixed: 'The rate and currency are fixed when the order is created.',
    createOrder: 'Create order and continue to payment', signIn: 'Sign in to check out', signInNote: 'Your cart is preserved through sign-in and registration.',
    demo: 'Demo mode: no real charges. Cart, orders and session reset when you reload the page.',
    updated: 'Prices updated. Review the total before checking out.', refresh: 'Update cart prices',
    verifyTitle: 'Demo email verification', verifyNote: 'An order needs a verified email. This button simulates verification; no email is sent.', verify: 'Simulate email verification',
    clientOnly: 'Checkout is for clients', clientOnlyText: 'Sign out of the trainer or administrator account and sign in as a client.',
    orders: 'My orders', ordersIntro: 'Saved purchase conditions and payment attempts.', noOrders: 'No orders yet', order: 'Order', details: 'Details',
    created: 'Created', pending: 'Awaiting payment', paid: 'Paid', cancelled: 'Cancelled', cancelledOrder: 'The unpaid order was cancelled. No access was issued.',
    review: 'Review your order', immutable: 'Prices, zones, terms, discount and exchange rate are fixed for this order.',
    payment: 'Simulated payment', paymentNote: 'Choose a test payment result. No card details are needed.',
    successChoice: 'Successful payment', failureChoice: 'Declined payment', pay: 'Pay in demo mode', retry: 'Retry payment',
    cancelOrder: 'Cancel unpaid order', success: 'Payment succeeded. Your access is in your account.', failed: 'Payment failed. No access was issued.',
    attempts: 'Payment attempts', succeeded: 'Succeeded', declined: 'Declined', access: 'Purchased access',
    memberships: 'Memberships', passes: 'Single visits', noPasses: 'No single visits yet.',
    accessIntro: 'Access validity and physical admission are separate.', unused: 'Unused', used: 'Used', expired: 'Expired', active: 'Active', upcoming: 'Upcoming',
    accessDates: 'Access period (Minsk time)', starts: 'Starts', ends: 'Ends, exclusive',
    redeemed: 'First admission recorded', noEntry: 'No admission recorded. Purchasing does not mean entering the club.', fixture: 'Demo status example without a linked order.',
    visitRule: 'One admission on your chosen date, during opening hours 07:00–23:00. Leaving ends the visit; re-entry is not included. Unused passes expire at the end of the day.',
    membershipRule: 'Independent visits to your selected zones during opening hours. Dates are not shifted automatically.',
    coaching: 'Coached training formats', group: 'Group sessions', individual: 'Group and individual sessions', independent: 'Independent exercise only',
    coachingNote: 'Bookings will arrive with the schedule and require the right zone, a valid membership and a place. Single visits do not qualify.',
    overlap: 'Membership dates can overlap only when their zones are different.',
    selectionStep: '1. Select', cartStep: '2. Cart', paymentStep: '3. Payment', accessStep: '4. Access',
    notFound: 'Record not found', notFoundText: 'Check the link or open your account list.',
    errors: {
      zones_required: 'Select at least one zone.', invalid_date: 'Choose a real date that is not before today in Minsk.',
      offer_unavailable: 'This option is no longer available. Edit it or remove it from your cart.',
      price_changed: 'The price or conditions changed. Update prices and review your total before checking out.',
      cart_changed: 'Your cart has changed. Refresh the cart and review its contents.', cart_empty: 'Add access to your cart.',
      invalid_promo: 'This promo code is unknown, expired or disabled.', membership_overlap: 'Membership dates overlap in the same zone. Edit the date or zones; check your active and upcoming memberships.',
      unauthorized: 'Your session ended. Sign in again.', forbidden: 'This action is for clients only.', verify_email: 'Complete demo email verification.',
      payment_declined: 'You selected a demo payment failure. Retry with a successful result.', order_changed: 'The order has already been paid or cancelled.',
      not_found: 'This record was not found in your account.', cart_limit: 'Your cart can hold up to 12 access items.',
      idempotency_conflict: 'The request parameters changed. Try again.', invalid_request: 'Invalid request.',
      invalid_currency: 'Choose an available currency.', rate_unavailable: 'The rate is unavailable. Choose BYN.', unknown: 'The action failed. Please try again.',
    },
  },
} as const

export function useCommerceCopy() {
  const { i18n } = useTranslation()
  const locale: 'ru' | 'en' = i18n.language === 'en' ? 'en' : 'ru'
  return { copy: commerceCopy[locale], locale }
}
