// Localized presentation copy for the shared homepage and membership cards. Commercial data uses the existing API.
export const homeCopy = {
  ru: {
    plans: 'Абонементы',
    title: 'Фитнес-клуб FORMA', intro: 'Тренажёрный зал, кардиозона и бассейн. Всё для самостоятельных занятий и тренировок с инструктором.',
    daily: 'Ежедневно', choose: 'Посмотреть абонементы', heroAlt: 'Вода крытого бассейна и большие окна', heroCaption: 'Бассейн', photoNote: 'Фото для концепции клуба',
    facilities: 'Залы и бассейн', facilitiesIntro: 'Три тренировочные зоны и общие раздевалки. Доступ во все зоны входит в каждый абонемент.',
    gym: 'Тренажёрный зал', gymText: 'Свободные веса, силовые тренажёры и пространство для функциональных упражнений. Самостоятельные занятия или работа с тренером.',
    gymDetail: 'Силовые и функциональные тренировки', gymAlt: 'Гантели и оборудование в тренажёрном зале',
    cardio: 'Кардиозона', cardioText: 'Беговые дорожки, велотренажёры и эллипсы для разминки и кардиотренировок. Предварительная запись на оборудование не требуется.',
    cardioDetail: 'Разминка и кардиотренировки', cardioAlt: 'Беговые дорожки у больших окон',
    pool: 'Водные программы', poolText: 'Плавание и аквааэробика. Посещение бассейна входит в абонемент; занятия с инструктором доступны в рамках условий выбранного тарифа.',
    poolDetail: 'Плавание и аквааэробика', poolAlt: 'Крытый бассейн с естественным освещением',
    changing: 'Раздевалки и душевые', changingText: 'Шкафчики для личных вещей, просторные раздевалки и душевые. Общие удобства для посетителей всех зон клуба.',
    changingDetail: 'Включены в посещение клуба', changingAlt: 'Индивидуальные шкафчики в раздевалке',
    teamLink: 'Познакомиться с тренерами', allPlans: 'Условия абонементов',
    plansIntro: 'Каждый абонемент включает тренажёрный зал, кардиозону, бассейн, раздевалки и душевые.',
    duration: 'Срок', training: 'Занятия с тренером', price: 'За весь срок', group: 'Групповые', individual: 'Групповые и индивидуальные',
    month1: '1 месяц', month3: '3 месяца', month12: '12 месяцев',
    selectPlan: 'Выбрать абонемент', individualOnly: 'Индивидуальные', independentOnly: 'Самостоятельные занятия',
    trainingNote: 'Занятия с тренером — по записи и в рамках условий тарифа.', noPlans: 'Сейчас нет доступных абонементов.',
    guestTitle: 'Первое посещение — бесплатно',
    guestIntro: 'Познакомьтесь с клубом и попробуйте самостоятельные занятия в зале, кардиозоне и бассейне.',
    guestTerms: 'Один гостевой визит для нового посетителя. По подтверждению администратора. Занятие с тренером не входит.',
    guestLoading: 'Загрузка формы…', guestAction: 'Оставить заявку', guestClose: 'Закрыть форму', guestFormTitle: 'Заявка на гостевой визит',
    guestDemo: 'Демонстрационная форма. Используйте вымышленные данные: заявка не отправляется.',
    guestName: 'Имя', guestPhone: 'Телефон', guestPhoneHint: 'С кодом страны, например +375 (29) 000-00-00.',
    guestSubmit: 'Проверить заявку', guestCancel: 'Отмена',
    guestNameInvalid: 'Введите имя от 1 до 80 символов.', guestPhoneInvalid: 'Введите телефон: от 7 до 15 цифр. Можно использовать +, пробелы, скобки и дефисы.',
    guestResult: 'Форма заполнена корректно. Это демонстрация: заявка не отправлена, посещение не забронировано.',
    demoNote: 'Демонстрационный каталог. Покупка и запись пока недоступны.',
    visiting: 'Перед посещением', visitingIntro: 'Коротко об абонементах и порядке занятий.',
    faqs: [
      { question: 'Какие зоны входят в абонемент?', answer: 'В каждый абонемент включены тренажёрный зал, кардиозона, бассейн, раздевалки и душевые. Состав занятий с тренером зависит от тарифа.' },
      { question: 'Можно ли заниматься самостоятельно?', answer: 'Да, в часы работы клуба и в пределах срока действия абонемента. Для самостоятельных посещений не предусмотрена запись на отдельные тренажёры или дорожки бассейна.' },
      { question: 'Как будет работать запись к тренеру?', answer: 'После подключения расписания вы сможете выбрать занятие и отправить заявку. Система проверит абонемент и наличие мест, затем тренер подтвердит или отклонит заявку. Сейчас запись ещё недоступна.' },
      { question: 'Какие правила отмены занятия предусмотрены?', answer: 'Клиент сможет отменить заявку не позднее чем за 12 часов до начала занятия. Для более поздней отмены потребуется обратиться к администратору.' },
    ],
    contactTitle: 'Контакты и часы работы', locationLabel: 'Расположение', hoursLabel: 'Часы работы', detailsNote: 'Точный адрес и контакты учебного клуба будут добавлены после согласования.',
    error: 'Не удалось загрузить данные клуба.', retry: 'Повторить', loading: 'Загрузка данных клуба…',
  },
  en: {
    plans: 'Memberships',
    title: 'FORMA fitness club', intro: 'A gym floor, cardio zone and swimming pool. Space for independent exercise and sessions with a coach.',
    daily: 'Daily', choose: 'View memberships', heroAlt: 'Water in an indoor pool with large windows', heroCaption: 'Swimming pool', photoNote: 'Club concept photography',
    facilities: 'Gym & pool', facilitiesIntro: 'Three training areas and shared changing rooms. Every membership includes access to all zones.',
    gym: 'Gym floor', gymText: 'Free weights, resistance machines and space for functional exercise. Train independently or work with a coach.',
    gymDetail: 'Strength and functional training', gymAlt: 'Dumbbells and equipment on the gym floor',
    cardio: 'Cardio zone', cardioText: 'Treadmills, exercise bikes and cross-trainers for warm-ups and cardio sessions. No equipment reservation is required.',
    cardioDetail: 'Warm-ups and cardio training', cardioAlt: 'Treadmills beside large windows',
    pool: 'Aquatics', poolText: 'Swimming and aqua aerobics. Pool access is included in every membership; coached sessions depend on your chosen plan.',
    poolDetail: 'Swimming and aqua aerobics', poolAlt: 'An indoor pool with natural light',
    changing: 'Changing rooms & showers', changingText: 'Lockers for personal belongings, spacious changing rooms and showers. Shared amenities for visitors to every zone.',
    changingDetail: 'Included in your club visit', changingAlt: 'Individual lockers in a changing room',
    teamLink: 'Meet the coaches', allPlans: 'Membership details',
    plansIntro: 'Every membership includes the gym floor, cardio zone, pool, changing rooms and showers.',
    duration: 'Term', training: 'Coached training', price: 'Full-term price', group: 'Group sessions', individual: 'Group and individual sessions',
    month1: '1 month', month3: '3 months', month12: '12 months',
    selectPlan: 'Choose membership', individualOnly: 'Individual sessions', independentOnly: 'Independent exercise',
    trainingNote: 'Coached sessions require booking and follow your plan’s conditions.', noPlans: 'No memberships are available at the moment.',
    guestTitle: 'Your first visit is free',
    guestIntro: 'Explore the club and try independent exercise in the gym, cardio zone and swimming pool.',
    guestTerms: 'One guest visit per new visitor, subject to administrator confirmation. A coached session is not included.',
    guestLoading: 'Loading form…', guestAction: 'Request a visit', guestClose: 'Close form', guestFormTitle: 'Guest visit request',
    guestDemo: 'Demo form. Use fictional details: no request will be sent.',
    guestName: 'Name', guestPhone: 'Phone number', guestPhoneHint: 'Include the country code, for example +375 (29) 000-00-00.',
    guestSubmit: 'Check request', guestCancel: 'Cancel',
    guestNameInvalid: 'Enter a name between 1 and 80 characters.', guestPhoneInvalid: 'Enter a phone number with 7–15 digits. You can use +, spaces, brackets and hyphens.',
    guestResult: 'The form is valid. This is a demo: no request was sent and no visit has been booked.',
    demoNote: 'Demo catalogue. Purchasing and booking are not yet available.',
    visiting: 'Before your visit', visitingIntro: 'Membership access and how training will work.',
    faqs: [
      { question: 'Which facilities are included?', answer: 'Every membership includes the gym floor, cardio zone, swimming pool, changing rooms and showers. The coached training formats depend on your plan.' },
      { question: 'Can I train independently?', answer: 'Yes, during opening hours while your membership is valid. Independent visits do not require reservations for individual machines or pool lanes.' },
      { question: 'How will coached-session booking work?', answer: 'Once the schedule is available, choose a session and send a request. The system will check your membership and available places before the coach approves or declines it. Booking is not available yet.' },
      { question: 'What cancellation rules are planned?', answer: 'Clients will be able to cancel at least 12 hours before a session starts. Later cancellations will require help from an administrator.' },
    ],
    contactTitle: 'Contact & opening hours', locationLabel: 'Location', hoursLabel: 'Opening hours', detailsNote: 'The coursework club’s street address and contact details will be added once agreed.',
    error: 'Could not load club information.', retry: 'Try again', loading: 'Loading club information…',
  },
} as const

export const facilityImages = {
  gym: '/images/club.jpg',
  cardio: '/images/design/cardio.jpg',
  pool: '/images/design/pool.jpg',
  changing: '/images/design/changing-room.jpg',
} as const

export type FacilityId = keyof typeof facilityImages
