// Localized presentation copy; commercial data comes through src/api/.
export const homeCopy = {
  "ru": {
    "plans": "Ваш формат посещения",
    "brand": "Фитнес-клуб FORMA",
    "title": "Тренажёрный зал, кардио и бассейн — в одном клубе.",
    "intro": "От первой тренировки до привычного ритма. Занимайтесь самостоятельно, пробуйте разные направления и находите свой формат вместе с тренером.",
    "daily": "Ежедневно",
    "choose": "Выбрать формат посещения",
    "heroAlt": "Пустой светлый тренажёрный зал с силовыми и кардиотренажёрами у больших окон",
    "heroCaption": "Ваш темп. Ваше пространство.",
    "photoNote": "FORMA — учебный проект. Фотографии показывают концепцию клуба; профили тренеров вымышлены, их портреты созданы с помощью ИИ.",
    "heroAction": "Первое посещение бесплатно",
    "heroTerms": "Для новых посетителей, по подтверждению администратора. Без занятия с тренером.",
    "directions": "Посмотреть пространства",
    "galleryHelp": "Переключайте фотографии кнопками или горизонтальным свайпом. На вкладках доступны клавиши ← →, Home и End.",
    "previousPhoto": "Предыдущее фото",
    "nextPhoto": "Следующее фото",
    "coaches": "Тренеры, с которыми проще начать",
    "coachesIntro": "Освоить движение, разобраться с техникой и выстроить занятия. Познакомьтесь с нашей командой.",
    "allCoaches": "Все тренеры",
    "coachesDemo": "Учебные профили. Портреты созданы с помощью ИИ и изображают вымышленных тренеров.",
    "coachesError": "Не удалось загрузить тренеров.",
    "coachesEmpty": "Профили тренеров скоро появятся.",
    "gym": "Тренажёрный зал",
    "gymText": "Свободные веса и силовые тренажёры для работы над техникой. Здесь же — пространство для функциональных упражнений, координации и баланса.",
    "gymDetail": "Сила · техника · движение",
    "gymAlt": "Мужчина выполняет выпад в зале со свободными весами у больших окон",
    "cardio": "Кардиозона",
    "cardioText": "Беговые дорожки, велотренажёры и эллипсы для разминки и кардиотренировок. Предварительная запись на оборудование не требуется.",
    "cardioDetail": "Разминка и кардиотренировки",
    "cardioAlt": "Беговые дорожки у больших окон",
    "pool": "Бассейн",
    "poolText": "Самостоятельное плавание или водные занятия с инструктором. Для самостоятельного плавания не нужно бронировать дорожку; занятия с тренером появятся в общем расписании.",
    "poolDetail": "Плавание и аквааэробика",
    "poolAlt": "Светлый крытый бассейн с бирюзовой водой и большими окнами",
    "changing": "Раздевалки и душевые",
    "changingText": "Переоденьтесь перед тренировкой, оставьте вещи в шкафчике и примите душ после занятия. Общие удобства доступны посетителям любой зоны.",
    "changingDetail": "Включены в посещение клуба",
    "changingAlt": "Индивидуальные шкафчики в раздевалке",
    "allPlans": "Все условия и демоабонементы",
    "plansIntro": "Абонемент на 1, 3 или 12 месяцев либо одно посещение. Выберите зоны и дату — полная стоимость сразу появится рядом.",
    "training": "Занятия с тренером",
    "price": "За весь срок",
    "group": "Групповые",
    "individual": "Групповые и индивидуальные",
    "month1": "1 месяц",
    "month3": "3 месяца",
    "month12": "12 месяцев",
    "selectPlan": "Выбрать абонемент",
    "individualOnly": "Индивидуальные",
    "independentOnly": "Самостоятельные занятия",
    "guestTitle": "Первое посещение — бесплатно",
    "guestIntro": "Познакомьтесь с клубом и попробуйте самостоятельные занятия в зале, кардиозоне и бассейне.",
    "guestTerms": "Один гостевой визит для нового посетителя, по подтверждению администратора. Без занятия с тренером и повторного входа. Это отдельное предложение, не платное разовое посещение.",
    "guestLoading": "Загрузка формы…",
    "guestAction": "Оставить заявку",
    "guestClose": "Закрыть форму",
    "guestFormTitle": "Заявка на гостевой визит",
    "guestDemo": "Демонстрационная форма. Используйте вымышленные данные: заявка не отправляется, данные исчезнут при закрытии или перезагрузке.",
    "guestName": "Имя",
    "guestPhone": "Телефон",
    "guestPhoneHint": "С кодом страны, например +375 (29) 000-00-00.",
    "guestSubmit": "Проверить заявку",
    "guestCancel": "Отмена",
    "guestNameInvalid": "Введите имя от 1 до 80 символов.",
    "guestPhoneInvalid": "Введите телефон: от 7 до 15 цифр. Можно использовать +, пробелы, скобки и дефисы.",
    "guestResult": "Форма заполнена корректно. Это демонстрация: заявка не отправлена, посещение не забронировано.",
    "visiting": "Перед посещением",
    "visitingIntro": "Первый раз часто начинается с вопросов. Собрали ответы, чтобы освоиться было проще.",
    "faqs": [
      {
        "question": "Я впервые в клубе. С чего начать?",
        "answer": "Новый посетитель может попробовать один бесплатный самостоятельный визит в зал, кардиозону и бассейн по подтверждению администратора. Занятие с тренером и повторный вход не включены. Форма выше демонстрационная: заявки пока не отправляются."
      },
      {
        "question": "Какие зоны можно выбрать?",
        "answer": "Зал + кардио, только бассейн или оба варианта. Это доступно для абонемента и разового посещения. Раздевалки, шкафчики и душевые всегда включены без доплаты."
      },
      {
        "question": "Как работает разовое посещение?",
        "answer": "Один вход в выбранную дату в часы работы клуба. Можно пользоваться всеми выбранными зонами до выхода; повторный вход не включён. Неиспользованное посещение истекает в конце выбранного дня."
      },
      {
        "question": "Включены ли занятия с тренером?",
        "answer": "Доступ в зоны предназначен для самостоятельных занятий. Для записи к тренеру нужны действующий на время занятия абонемент, нужная зона, разрешённый формат тренировки и свободное место. Разового посещения недостаточно. Выберите занятие в расписании и дождитесь подтверждения тренера."
      },
      {
        "question": "Можно ли уже оплатить выбранный вариант?",
        "answer": "Да, в деморежиме: добавьте вариант в корзину, войдите в аккаунт и создайте заказ. Можно проверить успешную оплату или отказ с повторной попыткой. Реальных списаний нет; данные сбрасываются при обновлении страницы."
      }
    ],
    "contactTitle": "Контакты и часы работы",
    "locationLabel": "Расположение",
    "hoursLabel": "Часы работы",
    "detailsNote": "Точный адрес и контакты учебного клуба будут добавлены после согласования.",
    "retry": "Повторить",
    "loading": "Загрузка данных клуба…",
    "spaces": "Пространства FORMA",
    "spacesIntro": "Силовая тренировка, свой кардиоритм или плавание. Посмотрите, где пройдёт ваше следующее занятие.",
    "gymAccess": "Зал и кардио — одна зона доступа. Занятия с тренером требуют подходящего абонемента и записи.",
    "gymAction": "Выбрать доступ в зал",
    "cardioAccess": "Входит в вариант «Зал + кардио», отдельно не оплачивается.",
    "cardioAction": "Посмотреть зал + кардио",
    "poolAccess": "Выберите бассейн отдельно или вместе с залом. Доступ в воду не включает автоматическую запись к тренеру.",
    "poolAction": "Выбрать доступ в бассейн",
    "changingAccess": "Раздевалки, шкафчики и душевые включены во все варианты без доплаты.",
    "visitOptions": "Все варианты посещения"
  },
  "en": {
    "plans": "Find your way to visit",
    "brand": "FORMA fitness club",
    "title": "Gym, cardio and swimming. All in one club.",
    "intro": "From your first workout to your everyday routine. Train independently, try something different and find your way with a coach.",
    "daily": "Daily",
    "choose": "Explore visit options",
    "heroAlt": "An empty, bright gym with strength and cardio equipment beside large windows",
    "heroCaption": "Your pace. Your space.",
    "photoNote": "FORMA is a coursework project. Facility photographs are concept imagery; coach profiles are fictional and their portraits are AI-generated.",
    "heroAction": "Try your first visit free",
    "heroTerms": "For new visitors, subject to administrator confirmation. A coached session is not included.",
    "directions": "Explore the spaces",
    "galleryHelp": "Use the photo buttons or swipe horizontally. On the tabs, use ← →, Home and End.",
    "previousPhoto": "Previous photo",
    "nextPhoto": "Next photo",
    "coaches": "A little guidance goes a long way",
    "coachesIntro": "Learn a movement, work on technique and build a routine. Meet the team who can help you get started.",
    "allCoaches": "All coaches",
    "coachesDemo": "Demo profiles. AI-generated portraits depict fictional coaches.",
    "coachesError": "Could not load coaches.",
    "coachesEmpty": "Coach profiles are coming soon.",
    "gym": "Gym floor",
    "gymText": "Free weights and resistance machines to work on your technique. There is also space for functional exercise, coordination and balance.",
    "gymDetail": "Strength · technique · movement",
    "gymAlt": "A man performing a lunge in a free-weight gym beside large windows",
    "cardio": "Cardio zone",
    "cardioText": "Treadmills, exercise bikes and cross-trainers for warm-ups and cardio sessions. No equipment reservation is required.",
    "cardioDetail": "Warm-ups and cardio training",
    "cardioAlt": "Treadmills beside large windows",
    "pool": "Pool",
    "poolText": "Independent swimming or water-based sessions with an instructor. Independent swimming needs no lane reservation; coached sessions will use the shared schedule.",
    "poolDetail": "Swimming and aqua aerobics",
    "poolAlt": "A bright indoor swimming pool with turquoise water and large windows",
    "changing": "Changing rooms & showers",
    "changingText": "Get changed before training, leave your belongings in a locker and shower afterwards. Shared amenities are available to visitors of every zone.",
    "changingDetail": "Included in your club visit",
    "changingAlt": "Individual lockers in a changing room",
    "allPlans": "All conditions and demo memberships",
    "plansIntro": "A membership for 1, 3 or 12 months, or a single visit. Choose your zones and date to see the full price alongside.",
    "training": "Coached training",
    "price": "Full-term price",
    "group": "Group sessions",
    "individual": "Group and individual sessions",
    "month1": "1 month",
    "month3": "3 months",
    "month12": "12 months",
    "selectPlan": "Choose membership",
    "individualOnly": "Individual sessions",
    "independentOnly": "Independent exercise",
    "guestTitle": "Your first visit is free",
    "guestIntro": "Explore the club and try independent exercise in the gym, cardio zone and swimming pool.",
    "guestTerms": "One guest visit per new visitor, subject to administrator confirmation. No coached session or re-entry. A separate offer from the paid single visit.",
    "guestLoading": "Loading form…",
    "guestAction": "Request a visit",
    "guestClose": "Close form",
    "guestFormTitle": "Guest visit request",
    "guestDemo": "Demo form. Use fictional details: no request is sent, and details disappear on close or reload.",
    "guestName": "Name",
    "guestPhone": "Phone number",
    "guestPhoneHint": "Include the country code, for example +375 (29) 000-00-00.",
    "guestSubmit": "Check request",
    "guestCancel": "Cancel",
    "guestNameInvalid": "Enter a name between 1 and 80 characters.",
    "guestPhoneInvalid": "Enter a phone number with 7–15 digits. You can use +, spaces, brackets and hyphens.",
    "guestResult": "The form is valid. This is a demo: no request was sent and no visit has been booked.",
    "visiting": "Before your visit",
    "visitingIntro": "A first visit often starts with a few questions. Here are some answers to help you feel at home.",
    "faqs": [
      {
        "question": "It is my first visit. Where do I start?",
        "answer": "New visitors can try one free independent visit to the gym, cardio zone and pool, subject to administrator confirmation. A coached session and re-entry are not included. The form above is a demonstration: requests are not sent yet."
      },
      {
        "question": "Which zones can I choose?",
        "answer": "Gym + cardio, pool only, or both. These options apply to memberships and single visits. Changing rooms, lockers and showers are always included at no extra charge."
      },
      {
        "question": "How does a single visit work?",
        "answer": "One admission on the selected date during opening hours. Use all your selected zones until you leave; re-entry is not included. An unused visit expires at the end of that day."
      },
      {
        "question": "Are coached sessions included?",
        "answer": "Zone access is for independent exercise. Booking a coach requires a membership valid at the session time, the required zone, training-format permission and an available place. A single visit is not enough. Choose a session in the schedule and wait for trainer approval."
      },
      {
        "question": "Can I pay for my selection now?",
        "answer": "Yes, in demo mode: add your selection to the cart, sign in and create an order. Try a successful payment or a decline followed by a retry. No real charges are made; data resets on page reload."
      }
    ],
    "contactTitle": "Contact & opening hours",
    "locationLabel": "Location",
    "hoursLabel": "Opening hours",
    "detailsNote": "The coursework club’s street address and contact details will be added once agreed.",
    "retry": "Try again",
    "loading": "Loading club information…",
    "spaces": "Spaces at FORMA",
    "spacesIntro": "A strength session, your own cardio rhythm or a swim. Take a look at the spaces for your next workout.",
    "gymAccess": "Gym and cardio are one access option. Coached sessions require an eligible membership and a booking.",
    "gymAction": "Explore gym access",
    "cardioAccess": "Included in Gym + cardio, with no separate fee.",
    "cardioAction": "Explore gym + cardio",
    "poolAccess": "Choose pool access on its own or with the gym. Zone access does not automatically include coached bookings.",
    "poolAction": "Explore pool access",
    "changingAccess": "Changing rooms, lockers and showers are included with every option, at no extra charge.",
    "visitOptions": "All visit options"
  }
} as const

export const facilityImages = {
  "gym": {
    "src": "/images/home/functional-training.webp",
    "width": 1536,
    "height": 1024
  },
  "cardio": {
    "src": "/images/design/cardio.jpg",
    "width": 1200,
    "height": 1800
  },
  "pool": {
    "src": "/images/home/pool-daylight.webp",
    "width": 1536,
    "height": 1024
  },
  "changing": {
    "src": "/images/design/changing-room.jpg",
    "width": 1200,
    "height": 800
  }
} as const

export const heroImage = '/images/home/hero-gym.webp'
export type HomeLocale = keyof typeof homeCopy
