// Localized presentation copy for the shared homepage and membership cards. Commercial data uses the existing API.
export const homeCopy = {
  ru: {
    plans: 'Абонементы',
    brand: 'Фитнес-клуб FORMA', title: 'Тренажёрный зал, кардио и бассейн — в одном клубе.', intro: 'От первой тренировки до привычного ритма. Занимайтесь самостоятельно, пробуйте разные направления и находите свой формат вместе с тренером.',
    daily: 'Ежедневно', choose: 'Посмотреть абонементы', heroAlt: 'Девушка с гантелями в тренировочном пространстве клуба', heroCaption: 'Место для вашего движения', photoNote: 'Иллюстрации концепции клуба',
    heroAction: 'Первое посещение бесплатно', heroTerms: 'Для новых посетителей, по подтверждению администратора. Без занятия с тренером.',
    directions: 'Как вы хотите тренироваться', directionsIntro: 'Работать с весом, двигаться в своём темпе или сменить зал на воду. Выбирайте занятие под своё настроение и задачи.',
    more: 'Как проходят занятия',
    activities: [
      { id: 'strength', title: 'Силовые тренировки', intro: 'Свободные веса и тренажёры для последовательной работы над силой и техникой.', format: 'Самостоятельно или с тренером', detail: 'Выбирайте упражнения с гантелями и на силовых тренажёрах. Тренер поможет разобраться в технике; формат занятий с ним зависит от абонемента.', alt: 'Гантели и оборудование в зоне силовых тренировок' },
      { id: 'functional', title: 'Функциональные упражнения', intro: 'Движения для всего тела: координация, баланс и работа с собственным весом.', format: 'В пространстве тренажёрного зала', detail: 'Сочетайте упражнения с собственным весом и свободными весами. Занимайтесь самостоятельно или с тренером в рамках условий тарифа.', alt: 'Мужчина выполняет выпад на тренировочном коврике' },
      { id: 'cardio', title: 'Кардиотренировки', intro: 'Разминка перед занятием или отдельная тренировка в комфортном для вас темпе.', format: 'Без записи на оборудование', detail: 'Беговые дорожки, велотренажёры и эллипсы доступны для самостоятельных занятий в часы работы клуба при действующем абонементе.', alt: 'Ряд беговых дорожек у больших окон' },
      { id: 'pool', title: 'Плавание и аквааэробика', intro: 'Плавание в своём ритме и водные занятия с инструктором — ещё один способ двигаться.', format: 'Самостоятельно или с инструктором', detail: 'Самостоятельное плавание не требует бронирования дорожек. Занятия с инструктором будут доступны по общему расписанию и условиям абонемента; сейчас запись ещё не подключена.', alt: 'Светлый крытый бассейн' },
    ],
    directionsNote: 'Запись на занятия с тренером появится вместе с расписанием. Формат занятий определяется абонементом.',
    gallery: 'Посмотрите клуб', galleryIntro: 'От свободных весов до воды. Познакомьтесь с пространствами, в которых проходят тренировки.',
    galleryLabel: 'Фотогалерея', galleryHelp: 'Листайте фотографии стрелками или свайпом. С клавиатуры: ← →, Home и End.', previousPhoto: 'Предыдущее фото', nextPhoto: 'Следующее фото',
    coaches: 'Тренеры, с которыми проще начать', coachesIntro: 'Освоить движение, разобраться с техникой и выстроить занятия. Познакомьтесь с нашей командой.', allCoaches: 'Все тренеры',
    coachesDemo: 'Учебные профили. Портреты созданы с помощью ИИ и изображают вымышленных тренеров.', coachesError: 'Не удалось загрузить тренеров.', coachesEmpty: 'Профили тренеров скоро появятся.',
    facilities: 'Залы и бассейн', facilitiesIntro: 'Три тренировочные зоны и общие раздевалки. Доступ во все зоны входит в каждый абонемент.',
    gym: 'Тренажёрный зал', gymText: 'Свободные веса, силовые тренажёры и пространство для функциональных упражнений. Самостоятельные занятия или работа с тренером.',
    gymDetail: 'Силовые и функциональные тренировки', gymAlt: 'Гантели и оборудование в тренажёрном зале',
    cardio: 'Кардиозона', cardioText: 'Беговые дорожки, велотренажёры и эллипсы для разминки и кардиотренировок. Предварительная запись на оборудование не требуется.',
    cardioDetail: 'Разминка и кардиотренировки', cardioAlt: 'Беговые дорожки у больших окон',
    pool: 'Водные программы', poolText: 'Плавание и аквааэробика. Посещение бассейна входит в абонемент; занятия с инструктором доступны в рамках условий выбранного тарифа.',
    poolDetail: 'Плавание и аквааэробика', poolAlt: 'Крытый бассейн с естественным освещением',
    changing: 'Раздевалки и душевые', changingText: 'Шкафчики для личных вещей, просторные раздевалки и душевые. Общие удобства для посетителей всех зон клуба.',
    changingDetail: 'Включены в посещение клуба', changingAlt: 'Индивидуальные шкафчики в раздевалке',
    teamLink: 'Познакомиться с тренерами', allPlans: 'Условия абонементов',
    plansIntro: 'Каждый абонемент включает тренажёрный зал, кардиозону, бассейн, раздевалки и душевые.',
    duration: 'Срок', training: 'Занятия с тренером', price: 'За весь срок', group: 'Групповые', individual: 'Групповые и индивидуальные',
    month1: '1 месяц', month3: '3 месяца', month12: '12 месяцев',
    selectPlan: 'Выбрать абонемент', individualOnly: 'Индивидуальные', independentOnly: 'Самостоятельные занятия',
    trainingNote: 'Занятия с тренером — по записи и в рамках условий тарифа.', noPlans: 'Сейчас нет доступных абонементов.',
    guestTitle: 'Первое посещение — бесплатно',
    guestIntro: 'Познакомьтесь с клубом и попробуйте самостоятельные занятия в зале, кардиозоне и бассейне.',
    guestTerms: 'Один гостевой визит для нового посетителя. По подтверждению администратора. Занятие с тренером не входит.',
    guestLoading: 'Загрузка формы…', guestAction: 'Оставить заявку', guestClose: 'Закрыть форму', guestFormTitle: 'Заявка на гостевой визит',
    guestDemo: 'Демонстрационная форма. Используйте вымышленные данные: заявка не отправляется.',
    guestName: 'Имя', guestPhone: 'Телефон', guestPhoneHint: 'С кодом страны, например +375 (29) 000-00-00.',
    guestSubmit: 'Проверить заявку', guestCancel: 'Отмена',
    guestNameInvalid: 'Введите имя от 1 до 80 символов.', guestPhoneInvalid: 'Введите телефон: от 7 до 15 цифр. Можно использовать +, пробелы, скобки и дефисы.',
    guestResult: 'Форма заполнена корректно. Это демонстрация: заявка не отправлена, посещение не забронировано.',
    demoNote: 'Демонстрационный каталог. Покупка и запись пока недоступны.',
    visiting: 'Перед посещением', visitingIntro: 'Коротко об абонементах и порядке занятий.',
    faqs: [
      { question: 'Какие зоны входят в абонемент?', answer: 'В каждый абонемент включены тренажёрный зал, кардиозона, бассейн, раздевалки и душевые. Состав занятий с тренером зависит от тарифа.' },
      { question: 'Можно ли заниматься самостоятельно?', answer: 'Да, в часы работы клуба и в пределах срока действия абонемента. Для самостоятельных посещений не предусмотрена запись на отдельные тренажёры или дорожки бассейна.' },
      { question: 'Как будет работать запись к тренеру?', answer: 'После подключения расписания вы сможете выбрать занятие и отправить заявку. Система проверит абонемент и наличие мест, затем тренер подтвердит или отклонит заявку. Сейчас запись ещё недоступна.' },
      { question: 'Какие правила отмены занятия предусмотрены?', answer: 'Клиент сможет отменить заявку не позднее чем за 12 часов до начала занятия. Для более поздней отмены потребуется обратиться к администратору.' },
    ],
    contactTitle: 'Контакты и часы работы', locationLabel: 'Расположение', hoursLabel: 'Часы работы', detailsNote: 'Точный адрес и контакты учебного клуба будут добавлены после согласования.',
    error: 'Не удалось загрузить данные клуба.', retry: 'Повторить', loading: 'Загрузка данных клуба…',
  },
  en: {
    plans: 'Memberships',
    brand: 'FORMA fitness club', title: 'Gym, cardio and swimming. All in one club.', intro: 'From your first workout to your everyday routine. Train independently, try something different and find your way with a coach.',
    daily: 'Daily', choose: 'View memberships', heroAlt: 'A woman training with dumbbells on the gym floor', heroCaption: 'Space to find your rhythm', photoNote: 'Club concept imagery',
    heroAction: 'Try your first visit free', heroTerms: 'For new visitors, subject to administrator confirmation. A coached session is not included.',
    directions: 'How do you like to move?', directionsIntro: 'Work with weights, find your pace or swap the gym for a swim. Choose an activity to suit your mood and goals.',
    more: 'About the sessions',
    activities: [
      { id: 'strength', title: 'Strength training', intro: 'Free weights and resistance machines for building strength and developing your technique.', format: 'On your own or with a coach', detail: 'Explore dumbbell exercises and resistance machines. A coach can help with technique; the coached session formats depend on your membership.', alt: 'Dumbbells and strength training equipment' },
      { id: 'functional', title: 'Functional exercise', intro: 'Whole-body movement: coordination, balance and exercises using your own body weight.', format: 'On the gym floor', detail: 'Combine bodyweight movements with free weights. Train independently or work with a coach within your membership conditions.', alt: 'A man performing a lunge on an exercise mat' },
      { id: 'cardio', title: 'Cardio training', intro: 'Warm up before your session or enjoy a standalone workout at your own pace.', format: 'No equipment reservations', detail: 'Treadmills, exercise bikes and cross-trainers are available for independent exercise during opening hours with a valid membership.', alt: 'Treadmills beside large windows' },
      { id: 'pool', title: 'Swimming & aqua aerobics', intro: 'Independent swimming and water-based sessions with an instructor offer another way to move.', format: 'On your own or with an instructor', detail: 'Independent swimming does not require lane reservations. Coached sessions will follow the shared schedule and your membership conditions; booking is not available yet.', alt: 'A bright indoor swimming pool' },
    ],
    directionsNote: 'Coached-session booking will be available with the schedule. Session formats depend on your membership.',
    gallery: 'Take a look around', galleryIntro: 'From free weights to the water. Explore the spaces where your training takes place.',
    galleryLabel: 'Photo carousel', galleryHelp: 'Use the buttons or swipe to browse. Keyboard: ← →, Home and End.', previousPhoto: 'Previous photo', nextPhoto: 'Next photo',
    coaches: 'A little guidance goes a long way', coachesIntro: 'Learn a movement, work on technique and build a routine. Meet the team who can help you get started.', allCoaches: 'All coaches',
    coachesDemo: 'Demo profiles. AI-generated portraits depict fictional coaches.', coachesError: 'Could not load coaches.', coachesEmpty: 'Coach profiles are coming soon.',
    facilities: 'Gym & pool', facilitiesIntro: 'Three training areas and shared changing rooms. Every membership includes access to all zones.',
    gym: 'Gym floor', gymText: 'Free weights, resistance machines and space for functional exercise. Train independently or work with a coach.',
    gymDetail: 'Strength and functional training', gymAlt: 'Dumbbells and equipment on the gym floor',
    cardio: 'Cardio zone', cardioText: 'Treadmills, exercise bikes and cross-trainers for warm-ups and cardio sessions. No equipment reservation is required.',
    cardioDetail: 'Warm-ups and cardio training', cardioAlt: 'Treadmills beside large windows',
    pool: 'Aquatics', poolText: 'Swimming and aqua aerobics. Pool access is included in every membership; coached sessions depend on your chosen plan.',
    poolDetail: 'Swimming and aqua aerobics', poolAlt: 'An indoor pool with natural light',
    changing: 'Changing rooms & showers', changingText: 'Lockers for personal belongings, spacious changing rooms and showers. Shared amenities for visitors to every zone.',
    changingDetail: 'Included in your club visit', changingAlt: 'Individual lockers in a changing room',
    teamLink: 'Meet the coaches', allPlans: 'Membership details',
    plansIntro: 'Every membership includes the gym floor, cardio zone, pool, changing rooms and showers.',
    duration: 'Term', training: 'Coached training', price: 'Full-term price', group: 'Group sessions', individual: 'Group and individual sessions',
    month1: '1 month', month3: '3 months', month12: '12 months',
    selectPlan: 'Choose membership', individualOnly: 'Individual sessions', independentOnly: 'Independent exercise',
    trainingNote: 'Coached sessions require booking and follow your plan’s conditions.', noPlans: 'No memberships are available at the moment.',
    guestTitle: 'Your first visit is free',
    guestIntro: 'Explore the club and try independent exercise in the gym, cardio zone and swimming pool.',
    guestTerms: 'One guest visit per new visitor, subject to administrator confirmation. A coached session is not included.',
    guestLoading: 'Loading form…', guestAction: 'Request a visit', guestClose: 'Close form', guestFormTitle: 'Guest visit request',
    guestDemo: 'Demo form. Use fictional details: no request will be sent.',
    guestName: 'Name', guestPhone: 'Phone number', guestPhoneHint: 'Include the country code, for example +375 (29) 000-00-00.',
    guestSubmit: 'Check request', guestCancel: 'Cancel',
    guestNameInvalid: 'Enter a name between 1 and 80 characters.', guestPhoneInvalid: 'Enter a phone number with 7–15 digits. You can use +, spaces, brackets and hyphens.',
    guestResult: 'The form is valid. This is a demo: no request was sent and no visit has been booked.',
    demoNote: 'Demo catalogue. Purchasing and booking are not yet available.',
    visiting: 'Before your visit', visitingIntro: 'Membership access and how training will work.',
    faqs: [
      { question: 'Which facilities are included?', answer: 'Every membership includes the gym floor, cardio zone, swimming pool, changing rooms and showers. The coached training formats depend on your plan.' },
      { question: 'Can I train independently?', answer: 'Yes, during opening hours while your membership is valid. Independent visits do not require reservations for individual machines or pool lanes.' },
      { question: 'How will coached-session booking work?', answer: 'Once the schedule is available, choose a session and send a request. The system will check your membership and available places before the coach approves or declines it. Booking is not available yet.' },
      { question: 'What cancellation rules are planned?', answer: 'Clients will be able to cancel at least 12 hours before a session starts. Later cancellations will require help from an administrator.' },
    ],
    contactTitle: 'Contact & opening hours', locationLabel: 'Location', hoursLabel: 'Opening hours', detailsNote: 'The coursework club’s street address and contact details will be added once agreed.',
    error: 'Could not load club information.', retry: 'Try again', loading: 'Loading club information…',
  },
} as const

export const facilityImages = {
  gym: '/images/club.jpg',
  cardio: '/images/design/cardio.jpg',
  pool: '/images/design/pool.jpg',
  changing: '/images/design/changing-room.jpg',
} as const

export const heroImage = '/images/home/hero-training.webp'
export const activityImages = { strength: facilityImages.gym, functional: '/images/home/functional-training.webp', cardio: facilityImages.cardio, pool: facilityImages.pool } as const
export type HomeLocale = keyof typeof homeCopy
